
# **ASSIGNMENT BRIEF Hugo Hernández Moreno**

**Contexto**:


> El Instituto Nacional de meteorología nos encarga un trabajo de análisis para observar los embalses de la comunidad de Madrid y predecir si habrá sequía o no, para regular el consumo de agua antes de que aparezca el problema.



---

# **Resolución**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## **Ingesta de CSV's**


> Función para combinar varios archivos CSV ubicados en una carpeta en un solo DataFrame y guardar el resultado en un nuevo archivo CSV.

In [ ]:
import pandas as pd
import os
import numpy as np

def combinar_csv(ruta_carpeta, nombre_archivo_salida):
    lista_archivos = [f for f in os.listdir(ruta_carpeta) if f.endswith('.csv')]

    df_embalses = pd.DataFrame()

    for archivo in lista_archivos:
        ruta_archivo = os.path.join(ruta_carpeta, archivo)
        nombre_embalse = os.path.splitext(archivo)[0]

        try:
            df_temporal = pd.read_csv(ruta_archivo, sep=";", encoding='latin-1')
        except UnicodeDecodeError:
            try:
                df_temporal = pd.read_csv(ruta_archivo, sep=";", encoding='ISO-8859-1')
            except Exception as e:
                print(f"Could not read file {ruta_archivo} with common encodings: {e}")
                continue


        df_temporal['embalse'] = nombre_embalse

        df_embalses = pd.concat([df_embalses, df_temporal], ignore_index=True)


    df_embalses.to_csv(nombre_archivo_salida, index=False)

ruta_carpeta = '/content/drive/MyDrive/Classroom/1ºPHE(MARZO) CYBERSECURITY APPLIED COMPUTING UNIT 15 - ARTIFICIAL INTELLIGENCE & INTELLIGENT SYSTEMS/AB/csv'
nombre_archivo_salida = "mixembalses.csv"

combinar_csv(ruta_carpeta, nombre_archivo_salida)

In [ ]:
df_mixembalses = pd.read_csv("mixembalses.csv")
df_mixembalses

,ï»¿anio,mes,hec_cub,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,embalse,anio
0,1998.0,enero,"23,891",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioCofio_LaAcena,NaN
1,NaN,febrero,"23,816",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioCofio_LaAcena,NaN
2,NaN,marzo,"23,245",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioCofio_LaAcena,NaN
3,NaN,abril,"23,35",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioCofio_LaAcena,NaN
4,NaN,mayo,"23,678",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioCofio_LaAcena,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4071,(p): Provisional. (a): Avance. (e): Estimado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioManzanares_Santillana,NaN
4072,.. : No disponible. - : No existe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioManzanares_Santillana,NaN
4073,"Los aÃ±os intermedios que no se muestran, no t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioManzanares_Santillana,NaN
4074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioManzanares_Santillana,NaN
4075,Fuente: Canal de Isabel II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AguaEmbalsada_RioManzanares_Santillana,NaN

In [ ]:
df_mixembalses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4076 entries, 0 to 4075
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ï»¿anio      370 non-null    object
 1   mes          4010 non-null   object
 2   hec_cub      3889 non-null   object
 3   Unnamed: 3   0 non-null      float64
 4   Unnamed: 4   0 non-null      float64
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   0 non-null      float64
 7   Unnamed: 7   0 non-null      float64
 8   Unnamed: 8   0 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  0 non-null      float64
 13  Unnamed: 13  0 non-null      float64
 14  embalse      4076 non-null   object
 15  anio         29 non-null     object
dtypes: float64(11), object(5)
memory usage: 509.6+ KB

In [ ]:
df_mixembalses['embalse']
# Eliminamos 'AguaEmbalsada' del inicio de los valores en la columna 'embalse'
df_mixembalses['embalse'] = df_mixembalses['embalse'].str.replace('AguaEmbalsada_', '', regex=False)

# Eliminamos cualquier espacio en blanco restante al inicio o al final
df_mixembalses['embalse'] = df_mixembalses['embalse'].str.strip()

# Mostramos los primeros valores de la columna 'embalse' para verificar el cambio
print(df_mixembalses['embalse'].head())

0    RioCofio_LaAcena
1    RioCofio_LaAcena
2    RioCofio_LaAcena
3    RioCofio_LaAcena
4    RioCofio_LaAcena
Name: embalse, dtype: object

In [ ]:
df_mixembalses.rename(columns={'ï»¿anio': 'year', 'mes':'month','hec_cub':'cub_hec'}, inplace=True)
df_mixembalses

,year,month,cub_hec,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,embalse,anio
0,1998.0,enero,"23,891",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioCofio_LaAcena,NaN
1,NaN,febrero,"23,816",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioCofio_LaAcena,NaN
2,NaN,marzo,"23,245",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioCofio_LaAcena,NaN
3,NaN,abril,"23,35",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioCofio_LaAcena,NaN
4,NaN,mayo,"23,678",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioCofio_LaAcena,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4071,(p): Provisional. (a): Avance. (e): Estimado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioManzanares_Santillana,NaN
4072,.. : No disponible. - : No existe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioManzanares_Santillana,NaN
4073,"Los aÃ±os intermedios que no se muestran, no t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioManzanares_Santillana,NaN
4074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioManzanares_Santillana,NaN
4075,Fuente: Canal de Isabel II,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RioManzanares_Santillana,NaN

In [ ]:
print(df_mixembalses.columns)

df_mixembalses.drop(['Unnamed: 3', 'Unnamed: 4','Unnamed: 5','Unnamed: 6', 'Unnamed: 7','Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'anio'], axis=1, inplace=True)

df_mixembalses

Index(['year', 'month', 'cub_hec', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'embalse', 'anio'],
      dtype='object')

,year,month,cub_hec,embalse
0,1998.0,enero,"23,891",RioCofio_LaAcena
1,NaN,febrero,"23,816",RioCofio_LaAcena
2,NaN,marzo,"23,245",RioCofio_LaAcena
3,NaN,abril,"23,35",RioCofio_LaAcena
4,NaN,mayo,"23,678",RioCofio_LaAcena
...,...,...,...,...
4071,(p): Provisional. (a): Avance. (e): Estimado,NaN,NaN,RioManzanares_Santillana
4072,.. : No disponible. - : No existe,NaN,NaN,RioManzanares_Santillana
4073,"Los aÃ±os intermedios que no se muestran, no t...",NaN,NaN,RioManzanares_Santillana
4074,NaN,NaN,NaN,RioManzanares_Santillana
4075,Fuente: Canal de Isabel II,NaN,NaN,RioManzanares_Santillana

In [ ]:
# Verificamos conteo de registros por falta de datos.
print(df_mixembalses['embalse'].value_counts())

embalse
RioGuadalix_Pedrezuela               294
RioGuadarrama-Aulencia_LaJorosa      294
RioGuadarrama-Aulencia_Valmayor      294
RioGuadarrama-Aulencia_Navalmedio    294
RioJarama_ElVado                     294
RioLozoya_ElAtazar                   294
RioManzanares_Navacerrada            294
RioLozoya_ElVillar                   294
RioLozoya_LaPinilla                  294
RioLozoya_PuentesViejas              294
RioManzanares_Santillana             294
RioLozoya_Riosequillo                294
RioCofio_LaAcena                     288
RioLosMorales_LosMorales             260
Name: count, dtype: int64

In [ ]:
# Reducir todos los embalses a 288 filas
df_mixembalses_limpio = df_mixembalses.groupby('embalse').head(288).reset_index(drop=True)

In [ ]:
años_por_embalse = df_mixembalses_limpio.groupby('embalse')['year'].unique()

# Mostramos los datos de años de cada embalse para verificar años faltantes o información basura.
for embalse, años in años_por_embalse.items():
    print(f"{embalse}: {sorted([a for a in años if pd.notna(a)])}")

RioCofio_LaAcena: ['1998.0', '1999.0', '2000.0', '2001.0', '2002.0', '2003.0', '2004.0', '2005.0', '2006.0', '2007.0', '2008.0', '2009.0', '2010.0', '2011.0', '2012.0', '2013.0', '2014.0', '2015.0', '2016.0', '2017.0', '2018.0', '2019.0', '2020.0', '2021.0']
RioGuadalix_Pedrezuela: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioGuadarrama-Aulencia_LaJorosa: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioGuadarrama-Aulencia_Navalmedio: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioGuadarrama-Aulencia_Valmayor: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioJarama_ElVado: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioLosMorales_LosMorales: [' ', '(p): Provisional.  (a): Avance.  (e): Estimado ', '.. : No disponible.  - : No existe ', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', 'Fuente: Canal de Isabel II', 'Los aÃ±os intermedios que no se muestran, no tienen datos ', 'Observaciones : ']
RioLozoya_ElAtazar: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioLozoya_ElVillar: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioLozoya_LaPinilla: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioLozoya_PuentesViejas: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioLozoya_Riosequillo: []
RioManzanares_Navacerrada: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']
RioManzanares_Santillana: ['1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']

In [ ]:
# Comprobamos que RioLozoya_Riosequillo realmente esta vacío.
print(df_mixembalses.loc[df_mixembalses['embalse'] == 'RioLozoya_Riosequillo', 'year'])

3194    NaN
3195    NaN
3196    NaN
3197    NaN
3198    NaN
       ...
3483    NaN
3484    NaN
3485    NaN
3486    NaN
3487    NaN
Name: year, Length: 294, dtype: object

In [ ]:
# Verificamos el conteo de registros, objetivo cumplido.
print(df_mixembalses_limpio['embalse'].value_counts())

embalse
RioCofio_LaAcena                     288
RioGuadalix_Pedrezuela               288
RioGuadarrama-Aulencia_LaJorosa      288
RioGuadarrama-Aulencia_Navalmedio    288
RioGuadarrama-Aulencia_Valmayor      288
RioJarama_ElVado                     288
RioLozoya_ElAtazar                   288
RioLozoya_ElVillar                   288
RioLozoya_LaPinilla                  288
RioLozoya_PuentesViejas              288
RioManzanares_Navacerrada            288
RioLozoya_Riosequillo                288
RioManzanares_Santillana             288
RioLosMorales_LosMorales             260
Name: count, dtype: int64

In [ ]:
# Eliminamos valores basura y quedarnos solo con años válidos (1998-2021)
df_mixembalses['year'] = pd.to_numeric(df_mixembalses['year'], errors='coerce')  # convierte años válidos y pone NaN en el resto

# Eliminamos filas con valores basura no convertibles
df_mixembalses = df_mixembalses[df_mixembalses['year'].between(1998, 2021, inclusive='both') | df_mixembalses['year'].isna()]

# Aseguramos tipo entero con soporte para NA
df_mixembalses['year'] = df_mixembalses['year'].astype('Int64')

In [ ]:
# Filtramos los NA de RioLozoya_Riosequillo
mask = (df_mixembalses['embalse'] == 'RioLozoya_Riosequillo') & (df_mixembalses['year'].isna())

# Recortamos las filas sobrantes (quedarse con solo 288)
indices_para_rellenar = df_mixembalses.loc[mask].index[:288]

# Creamos la secuencia de años esperada (1998 a 2021, 12 veces cada uno)
años_riosequillo = [a for a in range(1998, 2022) for _ in range(12)]

# Asignamos los años a esos índices
df_mixembalses.loc[indices_para_rellenar, 'year'] = años_riosequillo

In [ ]:
# Eliminamos los NA sobrantes del embalse
df_mixembalses = df_mixembalses.drop(df_mixembalses.loc[mask].index[288:])

In [ ]:
# Revisamos años únicos de nuevo
for embalse, años in df_mixembalses.groupby('embalse')['year'].unique().items():
    print(f"{embalse}: {sorted([a for a in años if pd.notna(a)])}")

RioCofio_LaAcena: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioGuadalix_Pedrezuela: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioGuadarrama-Aulencia_LaJorosa: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioGuadarrama-Aulencia_Navalmedio: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioGuadarrama-Aulencia_Valmayor: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioJarama_ElVado: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioLosMorales_LosMorales: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018)]
RioLozoya_ElAtazar: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioLozoya_ElVillar: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioLozoya_LaPinilla: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioLozoya_PuentesViejas: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioLozoya_Riosequillo: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioManzanares_Navacerrada: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]
RioManzanares_Santillana: [np.int64(1998), np.int64(1999), np.int64(2000), np.int64(2001), np.int64(2002), np.int64(2003), np.int64(2004), np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]

In [ ]:
# Aqui podemos ver un cambio de 'object' a tipo 'Int64'.
df_mixembalses['year'].info()

<class 'pandas.core.series.Series'>
Index: 4070 entries, 0 to 4075
Series name: year
Non-Null Count  Dtype
--------------  -----
597 non-null    Int64
dtypes: Int64(1)
memory usage: 67.6 KB

In [ ]:
print(df_mixembalses['year'].unique())

<IntegerArray>
[1998, <NA>, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]
Length: 25, dtype: Int64

In [ ]:
# Finalmente verificamos que el embalse que no tenia valores de año ya los tiene.
print(df_mixembalses.loc[df_mixembalses['embalse'] == 'RioLozoya_Riosequillo', 'year'])

3194    1998
3195    1998
3196    1998
3197    1998
3198    1998
        ...
3477    2021
3478    2021
3479    2021
3480    2021
3481    2021
Name: year, Length: 288, dtype: Int64

In [ ]:
# DataFrame semilimpio
df_mixembalses

      year    month cub_hec                   embalse
0     1998    enero  23,891          RioCofio_LaAcena
1     <NA>  febrero  23,816          RioCofio_LaAcena
2     <NA>    marzo  23,245          RioCofio_LaAcena
3     <NA>    abril   23,35          RioCofio_LaAcena
4     <NA>     mayo  23,678          RioCofio_LaAcena
...    ...      ...     ...                       ...
4071  <NA>      NaN     NaN  RioManzanares_Santillana
4072  <NA>      NaN     NaN  RioManzanares_Santillana
4073  <NA>      NaN     NaN  RioManzanares_Santillana
4074  <NA>      NaN     NaN  RioManzanares_Santillana
4075  <NA>      NaN     NaN  RioManzanares_Santillana

[4070 rows x 4 columns]

In [ ]:
df_mixembalses[df_mixembalses['embalse'] == 'RioLozoya_Riosequillo']

      year       month cub_hec                embalse
3194  1998       enero  45,782  RioLozoya_Riosequillo
3195  1998     febrero   46,64  RioLozoya_Riosequillo
3196  1998       marzo  45,965  RioLozoya_Riosequillo
3197  1998       abril  46,209  RioLozoya_Riosequillo
3198  1998        mayo  43,954  RioLozoya_Riosequillo
...    ...         ...     ...                    ...
3477  2021      agosto     NaN  RioLozoya_Riosequillo
3478  2021  septiembre     NaN  RioLozoya_Riosequillo
3479  2021     octubre     NaN  RioLozoya_Riosequillo
3480  2021   noviembre     NaN  RioLozoya_Riosequillo
3481  2021   diciembre     NaN  RioLozoya_Riosequillo

[288 rows x 4 columns]

In [ ]:
# Dado que hay valores null en la columna 'year' pues hacemo un 'ffill' que rellenara los datos faltantes de años.
df_mixembalses['year'] = df_mixembalses['year'].ffill()
df_mixembalses.head(25)

    year       month cub_hec           embalse
0   1998       enero  23,891  RioCofio_LaAcena
1   1998     febrero  23,816  RioCofio_LaAcena
2   1998       marzo  23,245  RioCofio_LaAcena
3   1998       abril   23,35  RioCofio_LaAcena
4   1998        mayo  23,678  RioCofio_LaAcena
5   1998       junio  21,947  RioCofio_LaAcena
6   1998       julio  18,924  RioCofio_LaAcena
7   1998      agosto  15,802  RioCofio_LaAcena
8   1998  septiembre  13,085  RioCofio_LaAcena
9   1998     octubre  11,208  RioCofio_LaAcena
10  1998   noviembre   9,802  RioCofio_LaAcena
11  1998   diciembre   8,315  RioCofio_LaAcena
12  1999       enero     9,5  RioCofio_LaAcena
13  1999     febrero  11,823  RioCofio_LaAcena
14  1999       marzo   12,75  RioCofio_LaAcena
15  1999       abril  11,733  RioCofio_LaAcena
16  1999        mayo  12,366  RioCofio_LaAcena
17  1999       junio   9,996  RioCofio_LaAcena
18  1999       julio   5,747  RioCofio_LaAcena
19  1999      agosto   3,866  RioCofio_LaAcena
20  1999  septiembre   3,627  RioCofio_LaAcena
21  1999     octubre   3,807  RioCofio_LaAcena
22  1999   noviembre   4,668  RioCofio_LaAcena
23  1999   diciembre     6,1  RioCofio_LaAcena
24  2000       enero   7,496  RioCofio_LaAcena

In [ ]:
# Finalmente los años son identicos a las entradas.
df_mixembalses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4070 entries, 0 to 4075
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     4070 non-null   Int64
 1   month    4009 non-null   object
 2   cub_hec  3888 non-null   object
 3   embalse  4070 non-null   object
dtypes: Int64(1), object(3)
memory usage: 163.0+ KB

In [ ]:
# Los valores de cub_hec son object entonces para su manipulacion lo pasamos a float.
df_mixembalses['cub_hec'] = df_mixembalses['cub_hec'].astype(str).str.replace(',', '.', regex=False).str.strip().str.replace(' ', '', regex=False)

df_mixembalses['cub_hec'] = pd.to_numeric(df_mixembalses['cub_hec'], errors='coerce')

df_mixembalses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4070 entries, 0 to 4075
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     4070 non-null   Int64
 1   month    4009 non-null   object
 2   cub_hec  3876 non-null   float64
 3   embalse  4070 non-null   object
dtypes: Int64(1), float64(1), object(2)
memory usage: 163.0+ KB

In [ ]:
# Ahora en vez de una coma tienen un punto por ser numeros float.
df_mixembalses.head(24)

    year       month  cub_hec           embalse
0   1998       enero   23.891  RioCofio_LaAcena
1   1998     febrero   23.816  RioCofio_LaAcena
2   1998       marzo   23.245  RioCofio_LaAcena
3   1998       abril   23.350  RioCofio_LaAcena
4   1998        mayo   23.678  RioCofio_LaAcena
5   1998       junio   21.947  RioCofio_LaAcena
6   1998       julio   18.924  RioCofio_LaAcena
7   1998      agosto   15.802  RioCofio_LaAcena
8   1998  septiembre   13.085  RioCofio_LaAcena
9   1998     octubre   11.208  RioCofio_LaAcena
10  1998   noviembre    9.802  RioCofio_LaAcena
11  1998   diciembre    8.315  RioCofio_LaAcena
12  1999       enero    9.500  RioCofio_LaAcena
13  1999     febrero   11.823  RioCofio_LaAcena
14  1999       marzo   12.750  RioCofio_LaAcena
15  1999       abril   11.733  RioCofio_LaAcena
16  1999        mayo   12.366  RioCofio_LaAcena
17  1999       junio    9.996  RioCofio_LaAcena
18  1999       julio    5.747  RioCofio_LaAcena
19  1999      agosto    3.866  RioCofio_LaAcena
20  1999  septiembre    3.627  RioCofio_LaAcena
21  1999     octubre    3.807  RioCofio_LaAcena
22  1999   noviembre    4.668  RioCofio_LaAcena
23  1999   diciembre    6.100  RioCofio_LaAcena

In [ ]:
# Verificamos valores de month, igual que hicimos con 'year'.
print(df_mixembalses['month'].unique())

['enero' 'febrero' 'marzo' 'abril' 'mayo' 'junio' 'julio' 'agosto'
 'septiembre' 'octubre' 'noviembre' 'diciembre' ' ' nan
 'A partir del 1 de Octubre, comienzo del nuevo aÃ±o hidrolÃ³gico, no se considera este embalse, ya que no es del Canal de Isabel II SA']

In [ ]:
df_mixembalses['month'] = df_mixembalses['month'].str.lower().str.strip()

# Reemplazamos valores no válidos por NaN
valores_no_validos = ['',' ', 'nan', 'a partir del 1 de octubre, comienzo del nuevo aã±o hidrolã³gico, no se considera este embalse, ya que no es del canal de isabel ii sa']

df_mixembalses['month'] = df_mixembalses['month'].replace(valores_no_validos, pd.NA)

# Mostramos los valores únicos para verificar
print(df_mixembalses['month'].unique())

['enero' 'febrero' 'marzo' 'abril' 'mayo' 'junio' 'julio' 'agosto'
 'septiembre' 'octubre' 'noviembre' 'diciembre' <NA> nan]

In [ ]:
# Mostramos filas donde 'month' es nulo (NaN o <NA>)
df_nulos_mes = df_mixembalses[df_mixembalses['month'].isna()]

print(df_nulos_mes)

      year month  cub_hec                   embalse
576   2021  <NA>      NaN    RioGuadalix_Pedrezuela
577   2021   NaN      NaN    RioGuadalix_Pedrezuela
578   2021   NaN      NaN    RioGuadalix_Pedrezuela
579   2021   NaN      NaN    RioGuadalix_Pedrezuela
580   2021   NaN      NaN    RioGuadalix_Pedrezuela
...    ...   ...      ...                       ...
4071  2021   NaN      NaN  RioManzanares_Santillana
4072  2021   NaN      NaN  RioManzanares_Santillana
4073  2021   NaN      NaN  RioManzanares_Santillana
4074  2021   NaN      NaN  RioManzanares_Santillana
4075  2021   NaN      NaN  RioManzanares_Santillana

[74 rows x 4 columns]

In [ ]:
# Obtenemos los índices de las filas con month nulo
indices_nulos = df_mixembalses[df_mixembalses['month'].isna()].index

# Para cada índice, mostramos filas anteriores, actuales y siguientes.
for idx in indices_nulos:
    print(f"Índice: {idx}")
    print(df_mixembalses.loc[max(idx-1,0):idx+1])
    print("-" * 40)

Índice: 576
     year      month  cub_hec                 embalse
575  2021  diciembre      NaN  RioGuadalix_Pedrezuela
576  2021       <NA>      NaN  RioGuadalix_Pedrezuela
577  2021        NaN      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 577
     year month  cub_hec                 embalse
576  2021  <NA>      NaN  RioGuadalix_Pedrezuela
577  2021   NaN      NaN  RioGuadalix_Pedrezuela
578  2021   NaN      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 578
     year month  cub_hec                 embalse
577  2021   NaN      NaN  RioGuadalix_Pedrezuela
578  2021   NaN      NaN  RioGuadalix_Pedrezuela
579  2021   NaN      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 579
     year month  cub_hec                 embalse
578  2021   NaN      NaN  RioGuadalix_Pedrezuela
579  2021   NaN      NaN  RioGuadalix_Pedrezuela
580  2021   NaN      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 580
     year month  cub_hec                 embalse
579  2021   NaN      NaN  RioGuadalix_Pedrezuela
580  2021   NaN      NaN  RioGuadalix_Pedrezuela
581  2021   NaN      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 581
     year  month  cub_hec                          embalse
580  2021    NaN      NaN           RioGuadalix_Pedrezuela
581  2021    NaN      NaN           RioGuadalix_Pedrezuela
582  1998  enero    6.572  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 870
     year      month  cub_hec                          embalse
869  2021  diciembre      NaN  RioGuadarrama-Aulencia_LaJorosa
870  2021       <NA>      NaN  RioGuadarrama-Aulencia_LaJorosa
871  2021        NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 871
     year month  cub_hec                          embalse
870  2021  <NA>      NaN  RioGuadarrama-Aulencia_LaJorosa
871  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
872  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 872
     year month  cub_hec                          embalse
871  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
872  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
873  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 873
     year month  cub_hec                          embalse
872  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
873  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
874  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 874
     year month  cub_hec                          embalse
873  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
874  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
875  2021   NaN      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 875
     year  month  cub_hec                            embalse
874  2021    NaN      NaN    RioGuadarrama-Aulencia_LaJorosa
875  2021    NaN      NaN    RioGuadarrama-Aulencia_LaJorosa
876  1998  enero    0.182  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1164
      year      month  cub_hec                            embalse
1163  2021  diciembre      NaN  RioGuadarrama-Aulencia_Navalmedio
1164  2021       <NA>      NaN  RioGuadarrama-Aulencia_Navalmedio
1165  2021        NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1165
      year month  cub_hec                            embalse
1164  2021  <NA>      NaN  RioGuadarrama-Aulencia_Navalmedio
1165  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1166  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1166
      year month  cub_hec                            embalse
1165  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1166  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1167  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1167
      year month  cub_hec                            embalse
1166  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1167  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1168  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1168
      year month  cub_hec                            embalse
1167  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1168  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1169  2021   NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1169
      year  month  cub_hec                            embalse
1168  2021    NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1169  2021    NaN      NaN  RioGuadarrama-Aulencia_Navalmedio
1170  1998  enero   118.99    RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1458
      year      month  cub_hec                          embalse
1457  2021  diciembre      NaN  RioGuadarrama-Aulencia_Valmayor
1458  2021       <NA>      NaN  RioGuadarrama-Aulencia_Valmayor
1459  2021        NaN      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1459
      year month  cub_hec                          embalse
1458  2021  <NA>      NaN  RioGuadarrama-Aulencia_Valmayor
1459  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1460  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1460
      year month  cub_hec                          embalse
1459  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1460  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1461  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1461
      year month  cub_hec                          embalse
1460  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1461  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1462  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1462
      year month  cub_hec                          embalse
1461  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1462  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1463  2021   NaN      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1463
      year  month  cub_hec                          embalse
1462  2021    NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1463  2021    NaN      NaN  RioGuadarrama-Aulencia_Valmayor
1464  1998  enero   45.882                 RioJarama_ElVado
----------------------------------------
Índice: 1752
      year      month  cub_hec           embalse
1751  2021  diciembre      NaN  RioJarama_ElVado
1752  2021       <NA>      NaN  RioJarama_ElVado
1753  2021        NaN      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1753
      year month  cub_hec           embalse
1752  2021  <NA>      NaN  RioJarama_ElVado
1753  2021   NaN      NaN  RioJarama_ElVado
1754  2021   NaN      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1754
      year month  cub_hec           embalse
1753  2021   NaN      NaN  RioJarama_ElVado
1754  2021   NaN      NaN  RioJarama_ElVado
1755  2021   NaN      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1755
      year month  cub_hec           embalse
1754  2021   NaN      NaN  RioJarama_ElVado
1755  2021   NaN      NaN  RioJarama_ElVado
1756  2021   NaN      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1756
      year month  cub_hec           embalse
1755  2021   NaN      NaN  RioJarama_ElVado
1756  2021   NaN      NaN  RioJarama_ElVado
1757  2021   NaN      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1757
      year  month  cub_hec                   embalse
1756  2021    NaN      NaN          RioJarama_ElVado
1757  2021    NaN      NaN          RioJarama_ElVado
1758  1998  enero    2.373  RioLosMorales_LosMorales
----------------------------------------
Índice: 2010
      year      month  cub_hec                   embalse
2009  2018  diciembre      NaN  RioLosMorales_LosMorales
2010  2018       <NA>      NaN  RioLosMorales_LosMorales
2011  2018        NaN      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2011
      year month  cub_hec                   embalse
2010  2018  <NA>      NaN  RioLosMorales_LosMorales
2011  2018   NaN      NaN  RioLosMorales_LosMorales
2012  2018   NaN      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2012
      year month  cub_hec                   embalse
2011  2018   NaN      NaN  RioLosMorales_LosMorales
2012  2018   NaN      NaN  RioLosMorales_LosMorales
2013  2018   NaN      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2013
      year month  cub_hec                   embalse
2012  2018   NaN      NaN  RioLosMorales_LosMorales
2013  2018   NaN      NaN  RioLosMorales_LosMorales
2014  2018   NaN      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2014
      year month  cub_hec                   embalse
2013  2018   NaN      NaN  RioLosMorales_LosMorales
2014  2018   NaN      NaN  RioLosMorales_LosMorales
2015  2018  <NA>      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2015
      year month  cub_hec                   embalse
2014  2018   NaN      NaN  RioLosMorales_LosMorales
2015  2018  <NA>      NaN  RioLosMorales_LosMorales
2016  2018   NaN      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2016
      year month  cub_hec                   embalse
2015  2018  <NA>      NaN  RioLosMorales_LosMorales
2016  2018   NaN      NaN  RioLosMorales_LosMorales
2017  2018   NaN      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2017
      year  month  cub_hec                   embalse
2016  2018    NaN      NaN  RioLosMorales_LosMorales
2017  2018    NaN      NaN  RioLosMorales_LosMorales
2018  1998  enero  326.784        RioLozoya_ElAtazar
----------------------------------------
Índice: 2306
      year      month  cub_hec             embalse
2305  2021  diciembre      NaN  RioLozoya_ElAtazar
2306  2021       <NA>      NaN  RioLozoya_ElAtazar
2307  2021        NaN      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2307
      year month  cub_hec             embalse
2306  2021  <NA>      NaN  RioLozoya_ElAtazar
2307  2021   NaN      NaN  RioLozoya_ElAtazar
2308  2021   NaN      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2308
      year month  cub_hec             embalse
2307  2021   NaN      NaN  RioLozoya_ElAtazar
2308  2021   NaN      NaN  RioLozoya_ElAtazar
2309  2021   NaN      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2309
      year month  cub_hec             embalse
2308  2021   NaN      NaN  RioLozoya_ElAtazar
2309  2021   NaN      NaN  RioLozoya_ElAtazar
2310  2021   NaN      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2310
      year month  cub_hec             embalse
2309  2021   NaN      NaN  RioLozoya_ElAtazar
2310  2021   NaN      NaN  RioLozoya_ElAtazar
2311  2021   NaN      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2311
      year  month  cub_hec             embalse
2310  2021    NaN      NaN  RioLozoya_ElAtazar
2311  2021    NaN      NaN  RioLozoya_ElAtazar
2312  1998  enero   22.741  RioLozoya_ElVillar
----------------------------------------
Índice: 2600
      year      month  cub_hec             embalse
2599  2021  diciembre      NaN  RioLozoya_ElVillar
2600  2021       <NA>      NaN  RioLozoya_ElVillar
2601  2021        NaN      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2601
      year month  cub_hec             embalse
2600  2021  <NA>      NaN  RioLozoya_ElVillar
2601  2021   NaN      NaN  RioLozoya_ElVillar
2602  2021   NaN      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2602
      year month  cub_hec             embalse
2601  2021   NaN      NaN  RioLozoya_ElVillar
2602  2021   NaN      NaN  RioLozoya_ElVillar
2603  2021   NaN      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2603
      year month  cub_hec             embalse
2602  2021   NaN      NaN  RioLozoya_ElVillar
2603  2021   NaN      NaN  RioLozoya_ElVillar
2604  2021   NaN      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2604
      year month  cub_hec             embalse
2603  2021   NaN      NaN  RioLozoya_ElVillar
2604  2021   NaN      NaN  RioLozoya_ElVillar
2605  2021   NaN      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2605
      year  month  cub_hec              embalse
2604  2021    NaN      NaN   RioLozoya_ElVillar
2605  2021    NaN      NaN   RioLozoya_ElVillar
2606  1998  enero   30.331  RioLozoya_LaPinilla
----------------------------------------
Índice: 2894
      year      month  cub_hec              embalse
2893  2021  diciembre      NaN  RioLozoya_LaPinilla
2894  2021       <NA>      NaN  RioLozoya_LaPinilla
2895  2021        NaN      NaN  RioLozoya_LaPinilla
----------------------------------------
Índice: 2895
      year month  cub_hec              embalse
2894  2021  <NA>      NaN  RioLozoya_LaPinilla
2895  2021   NaN      NaN  RioLozoya_LaPinilla
2896  2021   NaN      NaN  RioLozoya_LaPinilla
----------------------------------------
Índice: 2896
      year month  cub_hec              embalse
2895  2021   NaN      NaN  RioLozoya_LaPinilla
2896  2021   NaN      NaN  RioLozoya_LaPinilla
2897  2021   NaN      NaN  RioLozoya_LaPinilla
----------------------------------------
Índice: 2897
      year month  cub_hec              embalse
2896  2021   NaN      NaN  RioLozoya_LaPinilla
2897  2021   NaN      NaN  RioLozoya_LaPinilla
2898  2021   NaN      NaN  RioLozoya_LaPinilla
----------------------------------------
Índice: 2898
      year month  cub_hec              embalse
2897  2021   NaN      NaN  RioLozoya_LaPinilla
2898  2021   NaN      NaN  RioLozoya_LaPinilla
2899  2021   NaN      NaN  RioLozoya_LaPinilla
----------------------------------------
Índice: 2899
      year  month  cub_hec                  embalse
2898  2021    NaN      NaN      RioLozoya_LaPinilla
2899  2021    NaN      NaN      RioLozoya_LaPinilla
2900  1998  enero   41.769  RioLozoya_PuentesViejas
----------------------------------------
Índice: 3188
      year      month  cub_hec                  embalse
3187  2021  diciembre      NaN  RioLozoya_PuentesViejas
3188  2021       <NA>      NaN  RioLozoya_PuentesViejas
3189  2021        NaN      NaN  RioLozoya_PuentesViejas
----------------------------------------
Índice: 3189
      year month  cub_hec                  embalse
3188  2021  <NA>      NaN  RioLozoya_PuentesViejas
3189  2021   NaN      NaN  RioLozoya_PuentesViejas
3190  2021   NaN      NaN  RioLozoya_PuentesViejas
----------------------------------------
Índice: 3190
      year month  cub_hec                  embalse
3189  2021   NaN      NaN  RioLozoya_PuentesViejas
3190  2021   NaN      NaN  RioLozoya_PuentesViejas
3191  2021   NaN      NaN  RioLozoya_PuentesViejas
----------------------------------------
Índice: 3191
      year month  cub_hec                  embalse
3190  2021   NaN      NaN  RioLozoya_PuentesViejas
3191  2021   NaN      NaN  RioLozoya_PuentesViejas
3192  2021   NaN      NaN  RioLozoya_PuentesViejas
----------------------------------------
Índice: 3192
      year month  cub_hec                  embalse
3191  2021   NaN      NaN  RioLozoya_PuentesViejas
3192  2021   NaN      NaN  RioLozoya_PuentesViejas
3193  2021   NaN      NaN  RioLozoya_PuentesViejas
----------------------------------------
Índice: 3193
      year  month  cub_hec                  embalse
3192  2021    NaN      NaN  RioLozoya_PuentesViejas
3193  2021    NaN      NaN  RioLozoya_PuentesViejas
3194  1998  enero   45.782    RioLozoya_Riosequillo
----------------------------------------
Índice: 3776
      year      month  cub_hec                    embalse
3775  2021  diciembre      NaN  RioManzanares_Navacerrada
3776  2021       <NA>      NaN  RioManzanares_Navacerrada
3777  2021        NaN      NaN  RioManzanares_Navacerrada
----------------------------------------
Índice: 3777
      year month  cub_hec                    embalse
3776  2021  <NA>      NaN  RioManzanares_Navacerrada
3777  2021   NaN      NaN  RioManzanares_Navacerrada
3778  2021   NaN      NaN  RioManzanares_Navacerrada
----------------------------------------
Índice: 3778
      year month  cub_hec                    embalse
3777  2021   NaN      NaN  RioManzanares_Navacerrada
3778  2021   NaN      NaN  RioManzanares_Navacerrada
3779  2021   NaN      NaN  RioManzanares_Navacerrada
----------------------------------------
Índice: 3779
      year month  cub_hec                    embalse
3778  2021   NaN      NaN  RioManzanares_Navacerrada
3779  2021   NaN      NaN  RioManzanares_Navacerrada
3780  2021   NaN      NaN  RioManzanares_Navacerrada
----------------------------------------
Índice: 3780
      year month  cub_hec                    embalse
3779  2021   NaN      NaN  RioManzanares_Navacerrada
3780  2021   NaN      NaN  RioManzanares_Navacerrada
3781  2021   NaN      NaN  RioManzanares_Navacerrada
----------------------------------------
Índice: 3781
      year  month  cub_hec                    embalse
3780  2021    NaN      NaN  RioManzanares_Navacerrada
3781  2021    NaN      NaN  RioManzanares_Navacerrada
3782  1998  enero   76.953   RioManzanares_Santillana
----------------------------------------
Índice: 4070
      year      month  cub_hec                   embalse
4069  2021  diciembre      NaN  RioManzanares_Santillana
4070  2021       <NA>      NaN  RioManzanares_Santillana
4071  2021        NaN      NaN  RioManzanares_Santillana
----------------------------------------
Índice: 4071
      year month  cub_hec                   embalse
4070  2021  <NA>      NaN  RioManzanares_Santillana
4071  2021   NaN      NaN  RioManzanares_Santillana
4072  2021   NaN      NaN  RioManzanares_Santillana
----------------------------------------
Índice: 4072
      year month  cub_hec                   embalse
4071  2021   NaN      NaN  RioManzanares_Santillana
4072  2021   NaN      NaN  RioManzanares_Santillana
4073  2021   NaN      NaN  RioManzanares_Santillana
----------------------------------------
Índice: 4073
      year month  cub_hec                   embalse
4072  2021   NaN      NaN  RioManzanares_Santillana
4073  2021   NaN      NaN  RioManzanares_Santillana
4074  2021   NaN      NaN  RioManzanares_Santillana
----------------------------------------
Índice: 4074
      year month  cub_hec                   embalse
4073  2021   NaN      NaN  RioManzanares_Santillana
4074  2021   NaN      NaN  RioManzanares_Santillana
4075  2021   NaN      NaN  RioManzanares_Santillana
----------------------------------------
Índice: 4075
      year month  cub_hec                   embalse
4074  2021   NaN      NaN  RioManzanares_Santillana
4075  2021   NaN      NaN  RioManzanares_Santillana
----------------------------------------

In [ ]:
# Eliminamos las filas que no tienen valor en la columna 'month'.
df_mixembalses = df_mixembalses.dropna(subset=['month'])
df_mixembalses

      year       month  cub_hec                   embalse
0     1998       enero   23.891          RioCofio_LaAcena
1     1998     febrero   23.816          RioCofio_LaAcena
2     1998       marzo   23.245          RioCofio_LaAcena
3     1998       abril   23.350          RioCofio_LaAcena
4     1998        mayo   23.678          RioCofio_LaAcena
...    ...         ...      ...                       ...
4065  2021      agosto      NaN  RioManzanares_Santillana
4066  2021  septiembre      NaN  RioManzanares_Santillana
4067  2021     octubre      NaN  RioManzanares_Santillana
4068  2021   noviembre      NaN  RioManzanares_Santillana
4069  2021   diciembre      NaN  RioManzanares_Santillana

[3996 rows x 4 columns]

In [ ]:
# Revisamos de valores nulos en la columna 'month'
print(df_nulos_mes)
df_mixembalses.info()

      year month  cub_hec                   embalse
576   2021  <NA>      NaN    RioGuadalix_Pedrezuela
577   2021   NaN      NaN    RioGuadalix_Pedrezuela
578   2021   NaN      NaN    RioGuadalix_Pedrezuela
579   2021   NaN      NaN    RioGuadalix_Pedrezuela
580   2021   NaN      NaN    RioGuadalix_Pedrezuela
...    ...   ...      ...                       ...
4071  2021   NaN      NaN  RioManzanares_Santillana
4072  2021   NaN      NaN  RioManzanares_Santillana
4073  2021   NaN      NaN  RioManzanares_Santillana
4074  2021   NaN      NaN  RioManzanares_Santillana
4075  2021   NaN      NaN  RioManzanares_Santillana

[74 rows x 4 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 3996 entries, 0 to 4069
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     3996 non-null   Int64
 1   month    3996 non-null   object
 2   cub_hec  3876 non-null   float64
 3   embalse  3996 non-null   object
dtypes: Int64(1), float64(1), object(2)
memory usage: 160.0+ KB

In [ ]:
# Filtramos las filas donde el valor de 'cub_hec' es nulo
df_cub_hec_nulos = df_mixembalses[df_mixembalses['cub_hec'].isna()]
print(df_cub_hec_nulos)

      year       month  cub_hec                   embalse
279   2021       abril      NaN          RioCofio_LaAcena
280   2021        mayo      NaN          RioCofio_LaAcena
281   2021       junio      NaN          RioCofio_LaAcena
282   2021       julio      NaN          RioCofio_LaAcena
283   2021      agosto      NaN          RioCofio_LaAcena
...    ...         ...      ...                       ...
4065  2021      agosto      NaN  RioManzanares_Santillana
4066  2021  septiembre      NaN  RioManzanares_Santillana
4067  2021     octubre      NaN  RioManzanares_Santillana
4068  2021   noviembre      NaN  RioManzanares_Santillana
4069  2021   diciembre      NaN  RioManzanares_Santillana

[120 rows x 4 columns]

In [ ]:
# Obtenemos los índices de las filas con cub_hec nulo para buscar patrones.
indices_nulos = df_mixembalses[df_mixembalses['cub_hec'].isna()].index

for idx in indices_nulos:
    print(f"Índice: {idx}")
    inicio = max(idx - 1, 0)
    fin = min(idx + 1, len(df_mixembalses) - 1)
    print(df_mixembalses.loc[inicio:fin])
    print("-" * 40)

Índice: 279
     year  month  cub_hec           embalse
278  2021  marzo   23.731  RioCofio_LaAcena
279  2021  abril      NaN  RioCofio_LaAcena
280  2021   mayo      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 280
     year  month  cub_hec           embalse
279  2021  abril      NaN  RioCofio_LaAcena
280  2021   mayo      NaN  RioCofio_LaAcena
281  2021  junio      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 281
     year  month  cub_hec           embalse
280  2021   mayo      NaN  RioCofio_LaAcena
281  2021  junio      NaN  RioCofio_LaAcena
282  2021  julio      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 282
     year   month  cub_hec           embalse
281  2021   junio      NaN  RioCofio_LaAcena
282  2021   julio      NaN  RioCofio_LaAcena
283  2021  agosto      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 283
     year       month  cub_hec           embalse
282  2021       julio      NaN  RioCofio_LaAcena
283  2021      agosto      NaN  RioCofio_LaAcena
284  2021  septiembre      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 284
     year       month  cub_hec           embalse
283  2021      agosto      NaN  RioCofio_LaAcena
284  2021  septiembre      NaN  RioCofio_LaAcena
285  2021     octubre      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 285
     year       month  cub_hec           embalse
284  2021  septiembre      NaN  RioCofio_LaAcena
285  2021     octubre      NaN  RioCofio_LaAcena
286  2021   noviembre      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 286
     year      month  cub_hec           embalse
285  2021    octubre      NaN  RioCofio_LaAcena
286  2021  noviembre      NaN  RioCofio_LaAcena
287  2021  diciembre      NaN  RioCofio_LaAcena
----------------------------------------
Índice: 287
     year      month  cub_hec                 embalse
286  2021  noviembre      NaN        RioCofio_LaAcena
287  2021  diciembre      NaN        RioCofio_LaAcena
288  1998      enero   38.413  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 567
     year  month  cub_hec                 embalse
566  2021  marzo   37.489  RioGuadalix_Pedrezuela
567  2021  abril      NaN  RioGuadalix_Pedrezuela
568  2021   mayo      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 568
     year  month  cub_hec                 embalse
567  2021  abril      NaN  RioGuadalix_Pedrezuela
568  2021   mayo      NaN  RioGuadalix_Pedrezuela
569  2021  junio      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 569
     year  month  cub_hec                 embalse
568  2021   mayo      NaN  RioGuadalix_Pedrezuela
569  2021  junio      NaN  RioGuadalix_Pedrezuela
570  2021  julio      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 570
     year   month  cub_hec                 embalse
569  2021   junio      NaN  RioGuadalix_Pedrezuela
570  2021   julio      NaN  RioGuadalix_Pedrezuela
571  2021  agosto      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 571
     year       month  cub_hec                 embalse
570  2021       julio      NaN  RioGuadalix_Pedrezuela
571  2021      agosto      NaN  RioGuadalix_Pedrezuela
572  2021  septiembre      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 572
     year       month  cub_hec                 embalse
571  2021      agosto      NaN  RioGuadalix_Pedrezuela
572  2021  septiembre      NaN  RioGuadalix_Pedrezuela
573  2021     octubre      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 573
     year       month  cub_hec                 embalse
572  2021  septiembre      NaN  RioGuadalix_Pedrezuela
573  2021     octubre      NaN  RioGuadalix_Pedrezuela
574  2021   noviembre      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 574
     year      month  cub_hec                 embalse
573  2021    octubre      NaN  RioGuadalix_Pedrezuela
574  2021  noviembre      NaN  RioGuadalix_Pedrezuela
575  2021  diciembre      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 575
     year      month  cub_hec                 embalse
574  2021  noviembre      NaN  RioGuadalix_Pedrezuela
575  2021  diciembre      NaN  RioGuadalix_Pedrezuela
----------------------------------------
Índice: 861
     year  month  cub_hec                          embalse
860  2021  marzo     6.63  RioGuadarrama-Aulencia_LaJorosa
861  2021  abril      NaN  RioGuadarrama-Aulencia_LaJorosa
862  2021   mayo      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 862
     year  month  cub_hec                          embalse
861  2021  abril      NaN  RioGuadarrama-Aulencia_LaJorosa
862  2021   mayo      NaN  RioGuadarrama-Aulencia_LaJorosa
863  2021  junio      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 863
     year  month  cub_hec                          embalse
862  2021   mayo      NaN  RioGuadarrama-Aulencia_LaJorosa
863  2021  junio      NaN  RioGuadarrama-Aulencia_LaJorosa
864  2021  julio      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 864
     year   month  cub_hec                          embalse
863  2021   junio      NaN  RioGuadarrama-Aulencia_LaJorosa
864  2021   julio      NaN  RioGuadarrama-Aulencia_LaJorosa
865  2021  agosto      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 865
     year       month  cub_hec                          embalse
864  2021       julio      NaN  RioGuadarrama-Aulencia_LaJorosa
865  2021      agosto      NaN  RioGuadarrama-Aulencia_LaJorosa
866  2021  septiembre      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 866
     year       month  cub_hec                          embalse
865  2021      agosto      NaN  RioGuadarrama-Aulencia_LaJorosa
866  2021  septiembre      NaN  RioGuadarrama-Aulencia_LaJorosa
867  2021     octubre      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 867
     year       month  cub_hec                          embalse
866  2021  septiembre      NaN  RioGuadarrama-Aulencia_LaJorosa
867  2021     octubre      NaN  RioGuadarrama-Aulencia_LaJorosa
868  2021   noviembre      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 868
     year      month  cub_hec                          embalse
867  2021    octubre      NaN  RioGuadarrama-Aulencia_LaJorosa
868  2021  noviembre      NaN  RioGuadarrama-Aulencia_LaJorosa
869  2021  diciembre      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 869
     year      month  cub_hec                          embalse
868  2021  noviembre      NaN  RioGuadarrama-Aulencia_LaJorosa
869  2021  diciembre      NaN  RioGuadarrama-Aulencia_LaJorosa
----------------------------------------
Índice: 1155
      year  month  cub_hec                            embalse
1154  2021  marzo    0.291  RioGuadarrama-Aulencia_Navalmedio
1155  2021  abril      NaN  RioGuadarrama-Aulencia_Navalmedio
1156  2021   mayo      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1156
      year  month  cub_hec                            embalse
1155  2021  abril      NaN  RioGuadarrama-Aulencia_Navalmedio
1156  2021   mayo      NaN  RioGuadarrama-Aulencia_Navalmedio
1157  2021  junio      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1157
      year  month  cub_hec                            embalse
1156  2021   mayo      NaN  RioGuadarrama-Aulencia_Navalmedio
1157  2021  junio      NaN  RioGuadarrama-Aulencia_Navalmedio
1158  2021  julio      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1158
      year   month  cub_hec                            embalse
1157  2021   junio      NaN  RioGuadarrama-Aulencia_Navalmedio
1158  2021   julio      NaN  RioGuadarrama-Aulencia_Navalmedio
1159  2021  agosto      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1159
      year       month  cub_hec                            embalse
1158  2021       julio      NaN  RioGuadarrama-Aulencia_Navalmedio
1159  2021      agosto      NaN  RioGuadarrama-Aulencia_Navalmedio
1160  2021  septiembre      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1160
      year       month  cub_hec                            embalse
1159  2021      agosto      NaN  RioGuadarrama-Aulencia_Navalmedio
1160  2021  septiembre      NaN  RioGuadarrama-Aulencia_Navalmedio
1161  2021     octubre      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1161
      year       month  cub_hec                            embalse
1160  2021  septiembre      NaN  RioGuadarrama-Aulencia_Navalmedio
1161  2021     octubre      NaN  RioGuadarrama-Aulencia_Navalmedio
1162  2021   noviembre      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1162
      year      month  cub_hec                            embalse
1161  2021    octubre      NaN  RioGuadarrama-Aulencia_Navalmedio
1162  2021  noviembre      NaN  RioGuadarrama-Aulencia_Navalmedio
1163  2021  diciembre      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1163
      year      month  cub_hec                            embalse
1162  2021  noviembre      NaN  RioGuadarrama-Aulencia_Navalmedio
1163  2021  diciembre      NaN  RioGuadarrama-Aulencia_Navalmedio
----------------------------------------
Índice: 1449
      year  month  cub_hec                          embalse
1448  2021  marzo   111.96  RioGuadarrama-Aulencia_Valmayor
1449  2021  abril      NaN  RioGuadarrama-Aulencia_Valmayor
1450  2021   mayo      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1450
      year  month  cub_hec                          embalse
1449  2021  abril      NaN  RioGuadarrama-Aulencia_Valmayor
1450  2021   mayo      NaN  RioGuadarrama-Aulencia_Valmayor
1451  2021  junio      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1451
      year  month  cub_hec                          embalse
1450  2021   mayo      NaN  RioGuadarrama-Aulencia_Valmayor
1451  2021  junio      NaN  RioGuadarrama-Aulencia_Valmayor
1452  2021  julio      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1452
      year   month  cub_hec                          embalse
1451  2021   junio      NaN  RioGuadarrama-Aulencia_Valmayor
1452  2021   julio      NaN  RioGuadarrama-Aulencia_Valmayor
1453  2021  agosto      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1453
      year       month  cub_hec                          embalse
1452  2021       julio      NaN  RioGuadarrama-Aulencia_Valmayor
1453  2021      agosto      NaN  RioGuadarrama-Aulencia_Valmayor
1454  2021  septiembre      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1454
      year       month  cub_hec                          embalse
1453  2021      agosto      NaN  RioGuadarrama-Aulencia_Valmayor
1454  2021  septiembre      NaN  RioGuadarrama-Aulencia_Valmayor
1455  2021     octubre      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1455
      year       month  cub_hec                          embalse
1454  2021  septiembre      NaN  RioGuadarrama-Aulencia_Valmayor
1455  2021     octubre      NaN  RioGuadarrama-Aulencia_Valmayor
1456  2021   noviembre      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1456
      year      month  cub_hec                          embalse
1455  2021    octubre      NaN  RioGuadarrama-Aulencia_Valmayor
1456  2021  noviembre      NaN  RioGuadarrama-Aulencia_Valmayor
1457  2021  diciembre      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1457
      year      month  cub_hec                          embalse
1456  2021  noviembre      NaN  RioGuadarrama-Aulencia_Valmayor
1457  2021  diciembre      NaN  RioGuadarrama-Aulencia_Valmayor
----------------------------------------
Índice: 1743
      year  month  cub_hec           embalse
1742  2021  marzo    47.74  RioJarama_ElVado
1743  2021  abril      NaN  RioJarama_ElVado
1744  2021   mayo      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1744
      year  month  cub_hec           embalse
1743  2021  abril      NaN  RioJarama_ElVado
1744  2021   mayo      NaN  RioJarama_ElVado
1745  2021  junio      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1745
      year  month  cub_hec           embalse
1744  2021   mayo      NaN  RioJarama_ElVado
1745  2021  junio      NaN  RioJarama_ElVado
1746  2021  julio      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1746
      year   month  cub_hec           embalse
1745  2021   junio      NaN  RioJarama_ElVado
1746  2021   julio      NaN  RioJarama_ElVado
1747  2021  agosto      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1747
      year       month  cub_hec           embalse
1746  2021       julio      NaN  RioJarama_ElVado
1747  2021      agosto      NaN  RioJarama_ElVado
1748  2021  septiembre      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1748
      year       month  cub_hec           embalse
1747  2021      agosto      NaN  RioJarama_ElVado
1748  2021  septiembre      NaN  RioJarama_ElVado
1749  2021     octubre      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1749
      year       month  cub_hec           embalse
1748  2021  septiembre      NaN  RioJarama_ElVado
1749  2021     octubre      NaN  RioJarama_ElVado
1750  2021   noviembre      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1750
      year      month  cub_hec           embalse
1749  2021    octubre      NaN  RioJarama_ElVado
1750  2021  noviembre      NaN  RioJarama_ElVado
1751  2021  diciembre      NaN  RioJarama_ElVado
----------------------------------------
Índice: 1751
      year      month  cub_hec           embalse
1750  2021  noviembre      NaN  RioJarama_ElVado
1751  2021  diciembre      NaN  RioJarama_ElVado
----------------------------------------
Índice: 2007
      year       month  cub_hec                   embalse
2006  2018  septiembre    1.617  RioLosMorales_LosMorales
2007  2018     octubre      NaN  RioLosMorales_LosMorales
2008  2018   noviembre      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2008
      year      month  cub_hec                   embalse
2007  2018    octubre      NaN  RioLosMorales_LosMorales
2008  2018  noviembre      NaN  RioLosMorales_LosMorales
2009  2018  diciembre      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2009
      year      month  cub_hec                   embalse
2008  2018  noviembre      NaN  RioLosMorales_LosMorales
2009  2018  diciembre      NaN  RioLosMorales_LosMorales
----------------------------------------
Índice: 2297
      year  month  cub_hec             embalse
2296  2021  marzo  343.976  RioLozoya_ElAtazar
2297  2021  abril      NaN  RioLozoya_ElAtazar
2298  2021   mayo      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2298
      year  month  cub_hec             embalse
2297  2021  abril      NaN  RioLozoya_ElAtazar
2298  2021   mayo      NaN  RioLozoya_ElAtazar
2299  2021  junio      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2299
      year  month  cub_hec             embalse
2298  2021   mayo      NaN  RioLozoya_ElAtazar
2299  2021  junio      NaN  RioLozoya_ElAtazar
2300  2021  julio      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2300
      year   month  cub_hec             embalse
2299  2021   junio      NaN  RioLozoya_ElAtazar
2300  2021   julio      NaN  RioLozoya_ElAtazar
2301  2021  agosto      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2301
      year       month  cub_hec             embalse
2300  2021       julio      NaN  RioLozoya_ElAtazar
2301  2021      agosto      NaN  RioLozoya_ElAtazar
2302  2021  septiembre      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2302
      year       month  cub_hec             embalse
2301  2021      agosto      NaN  RioLozoya_ElAtazar
2302  2021  septiembre      NaN  RioLozoya_ElAtazar
2303  2021     octubre      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2303
      year       month  cub_hec             embalse
2302  2021  septiembre      NaN  RioLozoya_ElAtazar
2303  2021     octubre      NaN  RioLozoya_ElAtazar
2304  2021   noviembre      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2304
      year      month  cub_hec             embalse
2303  2021    octubre      NaN  RioLozoya_ElAtazar
2304  2021  noviembre      NaN  RioLozoya_ElAtazar
2305  2021  diciembre      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2305
      year      month  cub_hec             embalse
2304  2021  noviembre      NaN  RioLozoya_ElAtazar
2305  2021  diciembre      NaN  RioLozoya_ElAtazar
----------------------------------------
Índice: 2591
      year  month  cub_hec             embalse
2590  2021  marzo    19.54  RioLozoya_ElVillar
2591  2021  abril      NaN  RioLozoya_ElVillar
2592  2021   mayo      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2592
      year  month  cub_hec             embalse
2591  2021  abril      NaN  RioLozoya_ElVillar
2592  2021   mayo      NaN  RioLozoya_ElVillar
2593  2021  junio      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2593
      year  month  cub_hec             embalse
2592  2021   mayo      NaN  RioLozoya_ElVillar
2593  2021  junio      NaN  RioLozoya_ElVillar
2594  2021  julio      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2594
      year   month  cub_hec             embalse
2593  2021   junio      NaN  RioLozoya_ElVillar
2594  2021   julio      NaN  RioLozoya_ElVillar
2595  2021  agosto      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2595
      year       month  cub_hec             embalse
2594  2021       julio      NaN  RioLozoya_ElVillar
2595  2021      agosto      NaN  RioLozoya_ElVillar
2596  2021  septiembre      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2596
      year       month  cub_hec             embalse
2595  2021      agosto      NaN  RioLozoya_ElVillar
2596  2021  septiembre      NaN  RioLozoya_ElVillar
2597  2021     octubre      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2597
      year       month  cub_hec             embalse
2596  2021  septiembre      NaN  RioLozoya_ElVillar
2597  2021     octubre      NaN  RioLozoya_ElVillar
2598  2021   noviembre      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2598
      year      month  cub_hec             embalse
2597  2021    octubre      NaN  RioLozoya_ElVillar
2598  2021  noviembre      NaN  RioLozoya_ElVillar
2599  2021  diciembre      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2599
      year      month  cub_hec             embalse
2598  2021  noviembre      NaN  RioLozoya_ElVillar
2599  2021  diciembre      NaN  RioLozoya_ElVillar
----------------------------------------
Índice: 2885

In [ ]:
# Con los índices observados, detectamos que la mayoría de embalses finalizan sus datos en marzo de 2021, mientras que el embalse 'RioLosMorales_LosMorales' finaliza en 2018, por lo que lo verificamos.
los_morales = df_mixembalses[df_mixembalses['embalse'] == 'RioLosMorales_LosMorales']

# Mostramos las fechas únicas en las que hay datos
fechas_los_morales = los_morales[['year', 'month']].drop_duplicates().sort_values(by=['year', 'month'])

print(fechas_los_morales)

      year       month
1761  1998       abril
1765  1998      agosto
1769  1998   diciembre
1758  1998       enero
1759  1998     febrero
...    ...         ...
2000  2018       marzo
2002  2018        mayo
2008  2018   noviembre
2007  2018     octubre
2006  2018  septiembre

[252 rows x 2 columns]

In [ ]:
df_mixembalses.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3996 entries, 0 to 4069
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     3996 non-null   Int64
 1   month    3996 non-null   object
 2   cub_hec  3876 non-null   float64
 3   embalse  3996 non-null   object
dtypes: Int64(1), float64(1), object(2)
memory usage: 289.0+ KB

In [ ]:
  # Observamos los valores que tenemos en 'embalse'.
print(df_mixembalses['embalse'].unique())

['RioCofio_LaAcena' 'RioGuadalix_Pedrezuela'
 'RioGuadarrama-Aulencia_LaJorosa' 'RioGuadarrama-Aulencia_Navalmedio'
 'RioGuadarrama-Aulencia_Valmayor' 'RioJarama_ElVado'
 'RioLosMorales_LosMorales' 'RioLozoya_ElAtazar' 'RioLozoya_ElVillar'
 'RioLozoya_LaPinilla' 'RioLozoya_PuentesViejas' 'RioLozoya_Riosequillo'
 'RioManzanares_Navacerrada' 'RioManzanares_Santillana']

In [ ]:
# Volvemos a revisar el conteo de registros.
df_mixembalses['embalse'].value_counts()

embalse
RioCofio_LaAcena                     288
RioGuadalix_Pedrezuela               288
RioGuadarrama-Aulencia_LaJorosa      288
RioGuadarrama-Aulencia_Navalmedio    288
RioGuadarrama-Aulencia_Valmayor      288
RioJarama_ElVado                     288
RioLozoya_ElAtazar                   288
RioLozoya_ElVillar                   288
RioLozoya_LaPinilla                  288
RioLozoya_PuentesViejas              288
RioManzanares_Navacerrada            288
RioLozoya_Riosequillo                288
RioManzanares_Santillana             288
RioLosMorales_LosMorales             252
Name: count, dtype: int64

In [ ]:
# Filtramos el dataframe para eliminar las filas del embalse 'RioLosMorales_LosMorales' por falta de datos.
df_filtrado = df_mixembalses[df_mixembalses['embalse'] != 'RioLosMorales_LosMorales'].copy()

# Comprobamos que se eliminaron las filas
print(df_filtrado['embalse'].unique())
print(df_filtrado.info())

['RioCofio_LaAcena' 'RioGuadalix_Pedrezuela'
 'RioGuadarrama-Aulencia_LaJorosa' 'RioGuadarrama-Aulencia_Navalmedio'
 'RioGuadarrama-Aulencia_Valmayor' 'RioJarama_ElVado' 'RioLozoya_ElAtazar'
 'RioLozoya_ElVillar' 'RioLozoya_LaPinilla' 'RioLozoya_PuentesViejas'
 'RioLozoya_Riosequillo' 'RioManzanares_Navacerrada'
 'RioManzanares_Santillana']
<class 'pandas.core.frame.DataFrame'>
Index: 3744 entries, 0 to 4069
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     3744 non-null   Int64
 1   month    3744 non-null   object
 2   cub_hec  3627 non-null   float64
 3   embalse  3744 non-null   object
dtypes: Int64(1), float64(1), object(2)
memory usage: 149.9+ KB
None

In [ ]:
df_filtrado

      year       month  cub_hec                   embalse
0     1998       enero   23.891          RioCofio_LaAcena
1     1998     febrero   23.816          RioCofio_LaAcena
2     1998       marzo   23.245          RioCofio_LaAcena
3     1998       abril   23.350          RioCofio_LaAcena
4     1998        mayo   23.678          RioCofio_LaAcena
...    ...         ...      ...                       ...
4065  2021      agosto      NaN  RioManzanares_Santillana
4066  2021  septiembre      NaN  RioManzanares_Santillana
4067  2021     octubre      NaN  RioManzanares_Santillana
4068  2021   noviembre      NaN  RioManzanares_Santillana
4069  2021   diciembre      NaN  RioManzanares_Santillana

[3744 rows x 4 columns]

In [ ]:
# Verificamos los nulos por embalse dentro de cub_hec, por lo que llegamos a una conclusión.. los 9 counts seran los 9 meses del 2021, dado que sus registros acaban en marzo de 2021.
df_filtrado[df_filtrado['cub_hec'].isnull()]['embalse'].value_counts()

embalse
RioCofio_LaAcena                     9
RioGuadalix_Pedrezuela               9
RioGuadarrama-Aulencia_LaJorosa      9
RioGuadarrama-Aulencia_Navalmedio    9
RioGuadarrama-Aulencia_Valmayor      9
RioJarama_ElVado                     9
RioLozoya_ElAtazar                   9
RioLozoya_ElVillar                   9
RioLozoya_LaPinilla                  9
RioLozoya_PuentesViejas              9
RioLozoya_Riosequillo                9
RioManzanares_Navacerrada            9
RioManzanares_Santillana             9
Name: count, dtype: int64

In [ ]:
# Filtramos por meses y asi podemos eliminar esos nulos del 2021.
meses_permitidos = ['enero', 'febrero', 'marzo']

df_filtrado = df_filtrado[
    (df_filtrado['year'] < 2021) |
    ((df_filtrado['year'] == 2021) & (df_filtrado['month'].isin(meses_permitidos)))
]

In [ ]:
# Obtendremos los nulos (Objetivo: 0 Nulos)
print(df_filtrado['cub_hec'].isnull().sum())

0

In [ ]:
df_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3627 entries, 0 to 4060
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     3627 non-null   Int64
 1   month    3627 non-null   object
 2   cub_hec  3627 non-null   float64
 3   embalse  3627 non-null   object
dtypes: Int64(1), float64(1), object(2)
memory usage: 145.2+ KB

In [ ]:
df_filtrado.head(10)

   year       month  cub_hec           embalse
0  1998       enero   23.891  RioCofio_LaAcena
1  1998     febrero   23.816  RioCofio_LaAcena
2  1998       marzo   23.245  RioCofio_LaAcena
3  1998       abril   23.350  RioCofio_LaAcena
4  1998        mayo   23.678  RioCofio_LaAcena
5  1998       junio   21.947  RioCofio_LaAcena
6  1998       julio   18.924  RioCofio_LaAcena
7  1998      agosto   15.802  RioCofio_LaAcena
8  1998  septiembre   13.085  RioCofio_LaAcena
9  1998     octubre   11.208  RioCofio_LaAcena

In [ ]:
# Verificamos sus registros
print(df_filtrado['embalse'].value_counts())

embalse
RioCofio_LaAcena                     279
RioGuadalix_Pedrezuela               279
RioGuadarrama-Aulencia_LaJorosa      279
RioGuadarrama-Aulencia_Navalmedio    279
RioGuadarrama-Aulencia_Valmayor      279
RioJarama_ElVado                     279
RioLozoya_ElAtazar                   279
RioLozoya_ElVillar                   279
RioLozoya_LaPinilla                  279
RioLozoya_PuentesViejas              279
RioLozoya_Riosequillo                279
RioManzanares_Navacerrada            279
RioManzanares_Santillana             279
Name: count, dtype: int64

In [ ]:
# Verificamos sus registros por año.
print(df_filtrado['year'].value_counts().sort_index())

year
1998    156
1999    156
2000    156
2001    156
2002    156
2003    156
2004    156
2005    156
2006    156
2007    156
2008    156
2009    156
2010    156
2011    156
2012    156
2013    156
2014    156
2015    156
2016    156
2017    156
2018    156
2019    156
2020    156
2021     39
Name: count, dtype: Int64

In [ ]:
df_filtrado

      year      month  cub_hec                   embalse
0     1998      enero   23.891          RioCofio_LaAcena
1     1998    febrero   23.816          RioCofio_LaAcena
2     1998      marzo   23.245          RioCofio_LaAcena
3     1998      abril   23.350          RioCofio_LaAcena
4     1998       mayo   23.678          RioCofio_LaAcena
...    ...        ...      ...                       ...
4056  2020  noviembre   72.051  RioManzanares_Santillana
4057  2020  diciembre   80.703  RioManzanares_Santillana
4058  2021      enero   84.763  RioManzanares_Santillana
4059  2021    febrero   82.427  RioManzanares_Santillana
4060  2021      marzo   83.103  RioManzanares_Santillana

[3627 rows x 4 columns]

In [ ]:
# Para hacer el pivot necesitamos formar los meses de manera ordenada sino se ordenadaran alfabeticamente por defecto.
orden_meses = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
               'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']

In [ ]:
# Hacemos una copia del df y pasamos a Categorical los meses.
df_filtrado = df_filtrado.copy()
df_filtrado['month'] = pd.Categorical(
    df_filtrado['month'],
    categories=orden_meses,
    ordered=True
)

In [ ]:
# Creamos el df pivote donde los indices seran 'year' y 'month', mientras que las columnas seran los embalses.
df_pivot = df_filtrado.pivot_table(
    index=['year', 'month'],
    columns='embalse',
    values='cub_hec',
    observed=False
).reset_index()

## **Transformación de los datos (DataFrame Completo)**


> En este punto estamos en la transformación de los datos con un dataframe limpio y ordenado.

In [ ]:
# Mostramos el df pivote
df_pivot.head(25)

embalse,year,month,RioCofio_LaAcena,RioGuadalix_Pedrezuela,RioGuadarrama-Aulencia_LaJorosa,RioGuadarrama-Aulencia_Navalmedio,RioGuadarrama-Aulencia_Valmayor,RioJarama_ElVado,RioLozoya_ElAtazar,RioLozoya_ElVillar,RioLozoya_LaPinilla,RioLozoya_PuentesViejas,RioLozoya_Riosequillo,RioManzanares_Navacerrada,RioManzanares_Santillana
0,1998,enero,23.891,38.413,6.572,0.182,118.990,45.882,326.784,22.741,30.331,41.769,45.782,10.062,76.953
1,1998,febrero,23.816,38.104,6.462,0.617,119.578,46.043,327.590,21.550,30.254,41.442,46.640,10.114,78.440
2,1998,marzo,23.245,33.449,6.848,0.500,119.063,39.928,336.267,21.670,30.020,40.911,45.965,9.966,78.067
3,1998,abril,23.350,27.848,6.747,0.639,119.578,42.443,353.267,21.644,31.674,44.173,46.209,10.326,82.716
4,1998,mayo,23.678,23.009,7.041,0.625,120.833,49.165,391.448,21.925,35.518,50.395,43.954,10.989,85.453
5,1998,junio,21.947,21.130,6.718,0.559,109.389,41.751,412.483,19.654,29.596,43.927,41.359,9.647,78.627
6,1998,julio,18.924,14.083,6.072,0.643,95.295,24.442,405.935,12.448,28.418,43.706,43.338,7.982,77.602
7,1998,agosto,15.802,13.737,5.530,0.584,86.685,13.855,388.735,11.913,26.073,43.051,37.611,6.183,76.400
8,1998,septiembre,13.085,12.905,5.881,0.336,81.990,8.980,366.046,10.276,22.086,42.358,34.818,5.051,76.216
9,1998,octubre,11.208,10.461,6.006,0.191,78.129,13.340,336.358,13.147,21.860,34.594,35.689,4.348,76.307
10,1998,noviembre,9.802,9.170,5.957,0.257,74.970,12.720,306.506,11.903,22.839,32.867,38.217,3.635,77.046
11,1998,diciembre,8.315,7.679,6.095,0.370,71.615,16.277,277.656,14.065,23.005,32.255,40.743,3.277,79.096
12,1999,enero,9.500,6.745,5.794,0.546,67.243,21.140,254.298,14.308,25.399,34.359,43.806,3.593,78.721
13,1999,febrero,11.823,7.182,5.192,0.576,64.380,19.967,232.187,13.669,29.289,37.832,45.116,3.854,79.472
14,1999,marzo,12.750,6.220,5.930,0.203,59.910,22.558,235.053,19.629,30.020,41.049,45.904,5.266,79.756
15,1999,abril,11.733,4.874,6.624,0.543,59.351,24.412,244.001,19.654,30.331,41.049,45.995,5.439,78.347
16,1999,mayo,12.366,5.960,5.848,0.333,69.764,28.557,262.633,19.566,30.098,41.141,46.179,7.104,78.354
17,1999,junio,9.996,5.735,6.178,0.494,77.447,19.771,257.007,19.202,28.455,40.819,43.836,6.922,72.320
18,1999,julio,5.747,5.614,6.274,0.516,77.238,14.060,236.235,17.371,26.216,40.386,45.206,6.215,63.954
19,1999,agosto,3.866,5.430,5.457,0.471,73.102,9.749,216.535,15.576,25.611,39.889,44.577,4.497,55.169
20,1999,septiembre,3.627,5.395,4.535,0.470,76.201,7.881,196.024,15.212,25.505,39.443,44.547,3.268,48.825
21,1999,octubre,3.807,8.807,4.292,0.365,82.758,17.827,187.777,14.653,26.395,40.454,39.696,3.164,49.349
22,1999,noviembre,4.668,9.739,3.885,0.241,86.399,23.233,180.915,15.103,23.708,40.454,40.079,3.071,45.627
23,1999,diciembre,6.100,9.311,3.893,0.409,89.521,37.434,188.088,17.786,23.005,39.244,39.914,3.510,44.105
24,2000,enero,7.496,11.061,3.669,0.497,91.593,33.373,197.154,18.633,25.223,41.257,40.052,3.432,42.682

In [ ]:
# Mostramos info del df pivote
df_pivot.describe()

embalse,year,RioCofio_LaAcena,RioGuadalix_Pedrezuela,RioGuadarrama-Aulencia_LaJorosa,RioGuadarrama-Aulencia_Navalmedio,RioGuadarrama-Aulencia_Valmayor,RioJarama_ElVado,RioLozoya_ElAtazar,RioLozoya_ElVillar,RioLozoya_LaPinilla,RioLozoya_PuentesViejas,RioLozoya_Riosequillo,RioManzanares_Navacerrada,RioManzanares_Santillana
count,279.0,279.000000,279.000000,279.000000,279.000000,279.00000,279.000000,279.000000,279.000000,279.000000,279.000000,279.000000,279.000000,279.000000
mean,2009.129032,14.917538,23.872176,4.745143,0.384251,88.37257,26.462247,313.070312,17.837839,27.701907,37.322523,36.450957,6.408638,64.224921
std,6.724634,5.697118,10.108391,1.311262,0.082236,19.77569,14.676868,66.270411,4.625667,4.657266,10.865393,9.538406,2.181238,17.420686
min,1998.0,3.193000,4.874000,1.306000,0.182000,44.13300,6.546000,148.220000,0.000000,14.256000,1.955000,2.197000,1.906000,19.732000
25%,2003.0,11.031000,15.188000,3.891000,0.335000,72.82800,13.351500,274.502500,15.631500,24.322000,34.262000,33.449000,4.683500,50.678500
50%,2009.0,14.883000,24.826000,4.898000,0.373000,88.06500,22.786000,321.884000,19.127000,28.493000,41.049000,38.723000,6.261000,67.662000
75%,2015.0,19.536000,33.357500,5.878000,0.424000,104.25300,42.323500,361.446000,21.264500,31.276000,44.148000,43.046000,8.441000,78.814500
max,2021.0,23.912000,39.580000,7.041000,0.643000,121.72600,49.357000,423.885000,23.992000,36.553000,51.780000,48.552000,10.989000,90.304000

## **Transformación de los datos (DataFrame por Embalse)**


> En este punto estamos en la transformación de los datos por embalse, cada uno de ellos con su propio dataframe.

In [ ]:
# Creamos un diccionario con un DataFrame por cada embalse
dfs_por_embalse = {
    embalse: df_embalse.reset_index(drop=True)
    for embalse, df_embalse in df_filtrado.groupby('embalse')
}

In [ ]:
# Mostramos las Keys del dic.
print(dfs_por_embalse.keys())

dict_keys(['RioCofio_LaAcena', 'RioGuadalix_Pedrezuela', 'RioGuadarrama-Aulencia_LaJorosa', 'RioGuadarrama-Aulencia_Navalmedio', 'RioGuadarrama-Aulencia_Valmayor', 'RioJarama_ElVado', 'RioLozoya_ElAtazar', 'RioLozoya_ElVillar', 'RioLozoya_LaPinilla', 'RioLozoya_PuentesViejas', 'RioLozoya_Riosequillo', 'RioManzanares_Navacerrada', 'RioManzanares_Santillana'])

In [ ]:
# Probamos una key del dic.
dfs_por_embalse['RioLozoya_Riosequillo']

     year      month  cub_hec                embalse
0    1998      enero   45.782  RioLozoya_Riosequillo
1    1998    febrero   46.640  RioLozoya_Riosequillo
2    1998      marzo   45.965  RioLozoya_Riosequillo
3    1998      abril   46.209  RioLozoya_Riosequillo
4    1998       mayo   43.954  RioLozoya_Riosequillo
..    ...        ...      ...                    ...
274  2020  noviembre   35.890  RioLozoya_Riosequillo
275  2020  diciembre   38.857  RioLozoya_Riosequillo
276  2021      enero   43.689  RioLozoya_Riosequillo
277  2021    febrero   47.479  RioLozoya_Riosequillo
278  2021      marzo   46.455  RioLozoya_Riosequillo

[279 rows x 4 columns]

In [ ]:
# Recorremos el dic.
for nombre, df in dfs_por_embalse.items():
    print(f"Embalse: {nombre}")
    print(df.head())
    print("-" * 50)

Embalse: RioCofio_LaAcena
   year    month  cub_hec           embalse
0  1998    enero   23.891  RioCofio_LaAcena
1  1998  febrero   23.816  RioCofio_LaAcena
2  1998    marzo   23.245  RioCofio_LaAcena
3  1998    abril   23.350  RioCofio_LaAcena
4  1998     mayo   23.678  RioCofio_LaAcena
--------------------------------------------------
Embalse: RioGuadalix_Pedrezuela
   year    month  cub_hec                 embalse
0  1998    enero   38.413  RioGuadalix_Pedrezuela
1  1998  febrero   38.104  RioGuadalix_Pedrezuela
2  1998    marzo   33.449  RioGuadalix_Pedrezuela
3  1998    abril   27.848  RioGuadalix_Pedrezuela
4  1998     mayo   23.009  RioGuadalix_Pedrezuela
--------------------------------------------------
Embalse: RioGuadarrama-Aulencia_LaJorosa
   year    month  cub_hec                          embalse
0  1998    enero    6.572  RioGuadarrama-Aulencia_LaJorosa
1  1998  febrero    6.462  RioGuadarrama-Aulencia_LaJorosa
2  1998    marzo    6.848  RioGuadarrama-Aulencia_LaJorosa
3  1998    abril    6.747  RioGuadarrama-Aulencia_LaJorosa
4  1998     mayo    7.041  RioGuadarrama-Aulencia_LaJorosa
--------------------------------------------------
Embalse: RioGuadarrama-Aulencia_Navalmedio
   year    month  cub_hec                            embalse
0  1998    enero    0.182  RioGuadarrama-Aulencia_Navalmedio
1  1998  febrero    0.617  RioGuadarrama-Aulencia_Navalmedio
2  1998    marzo    0.500  RioGuadarrama-Aulencia_Navalmedio
3  1998    abril    0.639  RioGuadarrama-Aulencia_Navalmedio
4  1998     mayo    0.625  RioGuadarrama-Aulencia_Navalmedio
--------------------------------------------------
Embalse: RioGuadarrama-Aulencia_Valmayor
   year    month  cub_hec                          embalse
0  1998    enero  118.990  RioGuadarrama-Aulencia_Valmayor
1  1998  febrero  119.578  RioGuadarrama-Aulencia_Valmayor
2  1998    marzo  119.063  RioGuadarrama-Aulencia_Valmayor
3  1998    abril  119.578  RioGuadarrama-Aulencia_Valmayor
4  1998     mayo  120.833  RioGuadarrama-Aulencia_Valmayor
--------------------------------------------------
Embalse: RioJarama_ElVado
   year    month  cub_hec           embalse
0  1998    enero   45.882  RioJarama_ElVado
1  1998  febrero   46.043  RioJarama_ElVado
2  1998    marzo   39.928  RioJarama_ElVado
3  1998    abril   42.443  RioJarama_ElVado
4  1998     mayo   49.165  RioJarama_ElVado
--------------------------------------------------
Embalse: RioLozoya_ElAtazar
   year    month  cub_hec             embalse
0  1998    enero  326.784  RioLozoya_ElAtazar
1  1998  febrero  327.590  RioLozoya_ElAtazar
2  1998    marzo  336.267  RioLozoya_ElAtazar
3  1998    abril  353.267  RioLozoya_ElAtazar
4  1998     mayo  391.448  RioLozoya_ElAtazar
--------------------------------------------------
Embalse: RioLozoya_ElVillar
   year    month  cub_hec             embalse
0  1998    enero   22.741  RioLozoya_ElVillar
1  1998  febrero   21.550  RioLozoya_ElVillar
2  1998    marzo   21.670  RioLozoya_ElVillar
3  1998    abril   21.644  RioLozoya_ElVillar
4  1998     mayo   21.925  RioLozoya_ElVillar
--------------------------------------------------
Embalse: RioLozoya_LaPinilla
   year    month  cub_hec              embalse
0  1998    enero   30.331  RioLozoya_LaPinilla
1  1998  febrero   30.254  RioLozoya_LaPinilla
2  1998    marzo   30.020  RioLozoya_LaPinilla
3  1998    abril   31.674  RioLozoya_LaPinilla
4  1998     mayo   35.518  RioLozoya_LaPinilla
--------------------------------------------------
Embalse: RioLozoya_PuentesViejas
   year    month  cub_hec                  embalse
0  1998    enero   41.769  RioLozoya_PuentesViejas
1  1998  febrero   41.442  RioLozoya_PuentesViejas
2  1998    marzo   40.911  RioLozoya_PuentesViejas
3  1998    abril   44.173  RioLozoya_PuentesViejas
4  1998     mayo   50.395  RioLozoya_PuentesViejas
--------------------------------------------------
Embalse: RioLozoya_Riosequillo
   year    month  cub_hec                embalse
0  1998    enero   45.782  RioLozoya_Riosequillo
1  1998  febrero   46.640  RioLozoya_Riosequillo
2  1998    marzo   45.965  RioLozoya_Riosequillo
3  1998    abril   46.209  RioLozoya_Riosequillo
4  1998     mayo   43.954  RioLozoya_Riosequillo
--------------------------------------------------
Embalse: RioManzanares_Navacerrada
   year    month  cub_hec                    embalse
0  1998    enero   10.062  RioManzanares_Navacerrada
1  1998  febrero   10.114  RioManzanares_Navacerrada
2  1998    marzo    9.966  RioManzanares_Navacerrada
3  1998    abril   10.326  RioManzanares_Navacerrada
4  1998     mayo   10.989  RioManzanares_Navacerrada
--------------------------------------------------
Embalse: RioManzanares_Santillana
   year    month  cub_hec                   embalse
0  1998    enero   76.953  RioManzanares_Santillana
1  1998  febrero   78.440  RioManzanares_Santillana
2  1998    marzo   78.067  RioManzanares_Santillana
3  1998    abril   82.716  RioManzanares_Santillana
4  1998     mayo   85.453  RioManzanares_Santillana
--------------------------------------------------

In [ ]:
embalses = list(dfs_por_embalse.keys())

dfs_por_embalse[embalses[12]]  # Embalses desde el index 0 hasta el 12...

     year      month  cub_hec                   embalse
0    1998      enero   76.953  RioManzanares_Santillana
1    1998    febrero   78.440  RioManzanares_Santillana
2    1998      marzo   78.067  RioManzanares_Santillana
3    1998      abril   82.716  RioManzanares_Santillana
4    1998       mayo   85.453  RioManzanares_Santillana
..    ...        ...      ...                       ...
274  2020  noviembre   72.051  RioManzanares_Santillana
275  2020  diciembre   80.703  RioManzanares_Santillana
276  2021      enero   84.763  RioManzanares_Santillana
277  2021    febrero   82.427  RioManzanares_Santillana
278  2021      marzo   83.103  RioManzanares_Santillana

[279 rows x 4 columns]



-----

## Graficar Resultados


> En este punto graficamos resultados para su analisis.



*   Gráfico de barras
*   Gráfico de líneas
*   Violin Plot

In [ ]:
import plotly.express as px

# Gráfico de barras por año de cada uno los embalses.
for embalse, df in dfs_por_embalse.items():
    fig = px.bar(
        df,
        x="year",
        y="cub_hec",
        color="month",
        title=f"Cantidad de agua embalsada por año - {embalse}",
        labels={"cub_hec": "Hectómetros cúbicos", "year": "Año", "month":"Mes"},
        color_discrete_sequence=px.colors.qualitative.Set3
    )
    fig.update_layout(template="plotly_white")
    fig.show()

In [ ]:
# Calculamos el volumen total acumulado por embalse
volumen_total = df_filtrado.groupby('embalse')['cub_hec'].sum().sort_values(ascending=False)
print("Volumen:", volumen_total)
print()

# Seleccionamos los 2 primeros
top_embalses = volumen_total.head(2).index.tolist()
print("Embalses más importantes:", top_embalses, )

print("Con un volumen:", volumen_total.head(2).values)

Volumen: embalse
RioLozoya_ElAtazar                   87346.617
RioGuadarrama-Aulencia_Valmayor      24655.947
RioManzanares_Santillana             17918.753
RioLozoya_PuentesViejas              10412.984
RioLozoya_Riosequillo                10169.817
RioLozoya_LaPinilla                   7728.832
RioJarama_ElVado                      7382.967
RioGuadalix_Pedrezuela                6660.337
RioLozoya_ElVillar                    4976.757
RioCofio_LaAcena                      4161.993
RioManzanares_Navacerrada             1788.010
RioGuadarrama-Aulencia_LaJorosa       1323.895
RioGuadarrama-Aulencia_Navalmedio      107.206
Name: cub_hec, dtype: float64

Embalses más importantes: ['RioLozoya_ElAtazar', 'RioGuadarrama-Aulencia_Valmayor']
Con un volumen: [87346.617 24655.947]

In [ ]:
# Filtramos el DataFrame solo con esos dos embalses
df_top = df_filtrado[df_filtrado['embalse'].isin(top_embalses)]

# Gráfico de lineas para todos los años de los dos embalses más importantes comparando estos.
fig = px.line(
    df_top,
    x='year',
    y='cub_hec',
    color='embalse',
    line_group='month',
    markers=True,
    title=f"Comparativa de los dos embalses más importantes: {top_embalses[0]} y {top_embalses[1]}",
    labels={"cub_hec": "Hectómetros cúbicos", "year": "Año"},
    color_discrete_sequence=px.colors.qualitative.Set1
)

fig.update_layout(
    template='plotly_white',
    title_font=dict(size=20),
    xaxis=dict(dtick=1),
    yaxis_title="Volumen (hm³)",
    xaxis_title="Año",
    height=500
)

fig.show()

In [ ]:
# Gráfico de lineas para todos los años de los dos embalses más importantes por meses.
for embalse in top_embalses:
    df_mes_a_mes = dfs_por_embalse[embalse]

    fig = px.line(
        df_mes_a_mes,
        x="year",
        y="cub_hec",
        color="month",
        markers=True,
        title=f"Volumen mensual por año - {embalse}",
        labels={"cub_hec": "Hectómetros cúbicos", "year": "Año", "month": "Mes"},
        color_discrete_sequence=px.colors.qualitative.Set2
    )

    fig.update_layout(
        template="plotly_white",
        xaxis=dict(dtick=1),
        height=500,
        title_font=dict(size=20)
    )

    fig.show()

In [ ]:
colores = px.colors.qualitative.Dark24

# Violin Plot: Mostrando por año la cantidad de agua embalsada.
for i, (embalse, df_embalse) in enumerate(dfs_por_embalse.items()):
    color = colores[i % len(colores)]

    fig = px.violin(
        df_embalse,
        x='year',
        y='cub_hec',
        box=True,
        points='all',
        hover_data=['month'],
        title=f'Distribución anual de agua embalsada - {embalse}',
        labels={'cub_hec': 'Hectómetros cúbicos', 'year': 'Año'},
        color_discrete_sequence=[color]
    )
    fig.update_traces(marker_color=color, line_color=color)
    fig.update_layout(template='plotly_white', xaxis=dict(type='category'), height=500)
    fig.show()



---

\

# **Algoritmos de Predicción**



> Aplicar un algoritmo de predicción temporal a cada uno de los
embalses.

*   Prophet
*   Arima -> SARIMA
*   LTSM

In [ ]:
df_embalse.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279 entries, 0 to 278
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   year     279 non-null    Int64
 1   month    279 non-null    category
 2   cub_hec  279 non-null    float64
 3   embalse  279 non-null    object
dtypes: Int64(1), category(1), float64(1), object(1)
memory usage: 7.6+ KB

\

## **Prophet**

In [ ]:
import plotly.graph_objects as go
from prophet import Prophet
import pandas as pd

meses_dict = {
    'enero': '01', 'febrero': '02', 'marzo': '03', 'abril': '04',
    'mayo': '05', 'junio': '06', 'julio': '07', 'agosto': '08',
    'septiembre': '09', 'octubre': '10', 'noviembre': '11', 'diciembre': '12'
}

# Diccionario para almacenar modelos y predicciones
resultados_prediccion = {}

for embalse, df_embalse in dfs_por_embalse.items():
    df_prophet = df_embalse.copy()

    # Convertir mes en número
    df_prophet['month_num'] = df_prophet['month'].map(meses_dict).astype(str)

    # Crear la columna ds (formato fecha)
    df_prophet['ds'] = pd.to_datetime(df_prophet['year'].astype(str) + '-' + df_prophet['month_num'] + '-01')

    df_prophet['y'] = df_prophet['cub_hec']
    df_prophet = df_prophet[['ds', 'y']].dropna()

    # Entrenar el modelo
    model = Prophet(yearly_seasonality=True, daily_seasonality=False, weekly_seasonality=False)
    model.fit(df_prophet)

    # Fechas futuras (12 años)
    future = model.make_future_dataframe(periods=12*12, freq='MS')
    forecast = model.predict(future)

    # Guardar resultados
    resultados_prediccion[embalse] = {
        'model': model,
        'forecast': forecast,
        'historical': df_prophet
    }

    print(f"Predicción completada para {embalse}")

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/zwrvdb8n.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/g6bk5a47.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=45992', 'data', 'file=/tmp/tmp5ng54lr6/zwrvdb8n.json', 'init=/tmp/tmp5ng54lr6/g6bk5a47.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_model8iry0w7n/prophet_model-20250625123135.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:35 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:35 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/mjh1p0yj.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/oo9ldp63.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=31596', 'data', 'file=/tmp/tmp5ng54lr6/mjh1p0yj.json', 'init=/tmp/tmp5ng54lr6/oo9ldp63.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_model7zzh2qox/prophet_model-20250625123136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/_765ajef.json

Predicción completada para RioCofio_LaAcena
Predicción completada para RioGuadalix_Pedrezuela

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/2qxj1hin.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52866', 'data', 'file=/tmp/tmp5ng54lr6/_765ajef.json', 'init=/tmp/tmp5ng54lr6/2qxj1hin.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_modelu210vfsu/prophet_model-20250625123136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/xpcaeos9.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/pmt7xxpw.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36132', 'data', 'file=/tmp/tmp5ng54lr6/xpcaeos9.json', 'init=/tmp/tmp5ng54lr6/pmt7xxpw.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_modelbl1hquv3/prophet_model-20250625123136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Predicción completada para RioGuadarrama-Aulencia_LaJorosa
Predicción completada para RioGuadarrama-Aulencia_Navalmedio

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/v5104kz_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/qjs_5tl4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=81339', 'data', 'file=/tmp/tmp5ng54lr6/v5104kz_.json', 'init=/tmp/tmp5ng54lr6/qjs_5tl4.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_modelvr9mawte/prophet_model-20250625123136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/0qcq73nf.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/k73jrbh6.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=42982', 'data', 'file=/tmp/tmp5ng54lr6/0qcq73nf.json', 'init=/tmp/tmp5ng54lr6/k73jrbh6.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_modelgqcn5dz3/prophet_model-20250625123136.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:36 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:36 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/q23nw8ah.json

Predicción completada para RioGuadarrama-Aulencia_Valmayor
Predicción completada para RioJarama_ElVado

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/r3lk1ocz.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=41092', 'data', 'file=/tmp/tmp5ng54lr6/q23nw8ah.json', 'init=/tmp/tmp5ng54lr6/r3lk1ocz.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_model7a7j7q4o/prophet_model-20250625123137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/jhm0e29s.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/bx0jj6hy.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=19618', 'data', 'file=/tmp/tmp5ng54lr6/jhm0e29s.json', 'init=/tmp/tmp5ng54lr6/bx0jj6hy.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_model42e0ciy1/prophet_model-20250625123137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Predicción completada para RioLozoya_ElAtazar
Predicción completada para RioLozoya_ElVillar

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/f9qq5ebv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/1nlefik4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=69267', 'data', 'file=/tmp/tmp5ng54lr6/f9qq5ebv.json', 'init=/tmp/tmp5ng54lr6/1nlefik4.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_modelswotq75p/prophet_model-20250625123137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/n4lotv6_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/r5usoacd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=56783', 'data', 'file=/tmp/tmp5ng54lr6/n4lotv6_.json', 'init=/tmp/tmp5ng54lr6/r5usoacd.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_modelwtnwk656/prophet_model-20250625123137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Predicción completada para RioLozoya_LaPinilla

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/ixw1vn3o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/vy9ab3wn.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=10915', 'data', 'file=/tmp/tmp5ng54lr6/ixw1vn3o.json', 'init=/tmp/tmp5ng54lr6/vy9ab3wn.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_model__wded43/prophet_model-20250625123137.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:37 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:37 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Predicción completada para RioLozoya_PuentesViejas

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/_g9xum6i.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/4dr_217b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=50584', 'data', 'file=/tmp/tmp5ng54lr6/_g9xum6i.json', 'init=/tmp/tmp5ng54lr6/4dr_217b.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_modelfxc9v46_/prophet_model-20250625123138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Predicción completada para RioLozoya_Riosequillo

DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/yfvigt4z.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/oojl2uuk.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=26382', 'data', 'file=/tmp/tmp5ng54lr6/yfvigt4z.json', 'init=/tmp/tmp5ng54lr6/oojl2uuk.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_model_0vuqmdy/prophet_model-20250625123138.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:38 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Predicción completada para RioManzanares_Navacerrada
Predicción completada para RioManzanares_Santillana

In [ ]:
# Graficamos la serie temporal de Prophet
for embalse, resultado in resultados_prediccion.items():
    historical = resultado['historical']
    forecast = resultado['forecast']

    fig = go.Figure()

    # Serie histórica
    fig.add_trace(go.Scatter(
        x=historical['ds'],
        y=historical['y'],
        mode='lines+markers',
        name='Histórico',
        line=dict(color='blue')
    ))

    # Predicción
    fig.add_trace(go.Scatter(
        x=forecast['ds'],
        y=forecast['yhat'],
        mode='lines',
        name='Predicción',
        line=dict(color='green', dash='dash')
    ))

    # Intervalo de confianza
    fig.add_trace(go.Scatter(
        x=forecast['ds'],
        y=forecast['yhat_lower'],
        mode='lines',
        name='Límite inferior',
        line=dict(color='lightgreen'),
        showlegend=False
    ))

    fig.add_trace(go.Scatter(
        x=forecast['ds'],
        y=forecast['yhat_upper'],
        mode='lines',
        name='Límite superior',
        fill='tonexty',
        line=dict(color='lightgreen'),
        showlegend=False
    ))

    # Layout
    fig.update_layout(
        title=f'Predicción de volumen embalsado - {embalse}',
        xaxis_title='Fecha',
        yaxis_title='Hectómetros cúbicos',
        template='plotly_white',
        height=500,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )

    fig.show()

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

y_true_total = []
y_pred_total = []

for embalse, resultado in resultados_prediccion.items():
    df_real = resultado['historical']
    df_pred = resultado['forecast']

    # Comparar solo en el histórico
    df_merge = pd.merge(df_real, df_pred[['ds', 'yhat']], on='ds', how='inner')

    y_true_total.extend(df_merge['y'].values)
    y_pred_total.extend(df_merge['yhat'].values)

# Convertir a arrays
y_true_total = np.array(y_true_total)
y_pred_total = np.array(y_pred_total)

# Métricas
r2_total = r2_score(y_true_total, y_pred_total)
mae = mean_absolute_error(y_true_total, y_pred_total)
rmse = np.sqrt(mean_squared_error(y_true_total, y_pred_total))

# MAPE corregido
non_zero_mask = y_true_total != 0
mape = np.mean(np.abs((y_true_total[non_zero_mask] - y_pred_total[non_zero_mask]) / y_true_total[non_zero_mask])) * 100

# Mostramos métricas
print(f"\nMétricas globales del modelo Prophet:")
print(f"R²: {r2_total:.4f}")
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"MAPE: {mape:.2f}%")
print(f"Accuracy aproximada: {100 - mape:.2f}%")

Métricas globales del modelo Prophet:
R²: 0.9537
MAE: 8.66
RMSE: 17.64
MAPE: 36.08%
Accuracy aproximada: 63.92%

\

In [ ]:
from prophet import Prophet
import pandas as pd

# Preparar datos
meses_dict = {
    'enero': '01', 'febrero': '02', 'marzo': '03', 'abril': '04',
    'mayo': '05', 'junio': '06', 'julio': '07', 'agosto': '08',
    'septiembre': '09', 'octubre': '10', 'noviembre': '11', 'diciembre': '12'
}

df_fechas = df_pivot.copy()
df_fechas['month_num'] = df_fechas['month'].map(meses_dict).astype(str)
df_fechas['fecha'] = pd.to_datetime(df_fechas['year'].astype(str) + '-' + df_fechas['month_num'] + '-01')

columnas_embalses = [col for col in df_fechas.columns if col not in ['year', 'month', 'month_num', 'fecha']]
df_fechas['total'] = df_fechas[columnas_embalses].sum(axis=1, skipna=True)

# Renombrar para Prophet
fechas = df_fechas[['fecha', 'total']].rename(columns={'fecha': 'ds', 'total': 'y'})
fechas = fechas.dropna()

# Entrenar modelo
model = Prophet()
model.fit(fechas)

# Generar predicciones 12 años
proximas_fechas = model.make_future_dataframe(periods=144, freq='MS')
predicciones = model.predict(proximas_fechas)

# Separar predicciones futuras
predicciones_futuras = predicciones[predicciones['ds'] > fechas['ds'].max()]

print("Modelo Prophet entrenado")
print(f"Datos historicos: {len(fechas)} registros")
print(f"Predicciones futuras: {len(predicciones_futuras)} registros")

INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/ltt38trm.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp5ng54lr6/f7obae0e.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.11/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=40793', 'data', 'file=/tmp/tmp5ng54lr6/ltt38trm.json', 'init=/tmp/tmp5ng54lr6/f7obae0e.json', 'output', 'file=/tmp/tmp5ng54lr6/prophet_model1hl3th0d/prophet_model-20250625123141.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
12:31:41 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
12:31:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Modelo Prophet entrenado
Datos historicos: 279 registros
Predicciones futuras: 144 registros

In [ ]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Grafico principal
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=fechas['ds'],
    y=fechas['y'],
    mode='lines+markers',
    name='Datos Historicos',
    line=dict(color='blue', width=2)
))

fig.add_trace(go.Scatter(
    x=predicciones['ds'],
    y=predicciones['yhat'],
    mode='lines',
    name='Prediccion',
    line=dict(color='red', width=2, dash='dash')
))

fig.add_trace(go.Scatter(
    x=predicciones['ds'],
    y=predicciones['yhat_upper'],
    fill=None,
    mode='lines',
    line_color='rgba(0,0,0,0)',
    showlegend=False
))

fig.add_trace(go.Scatter(
    x=predicciones['ds'],
    y=predicciones['yhat_lower'],
    fill='tonexty',
    mode='lines',
    line_color='rgba(0,0,0,0)',
    name='Intervalo Confianza',
    fillcolor='rgba(255,0,0,0.2)'
))

fig.update_layout(
    title='Prediccion Volumen Embalses Madrid',
    xaxis_title='Fecha',
    yaxis_title='Capacidad (hm3)',
    template='plotly_white',
    height=700
)

fig.show()

# Grafico componentes
fig_comp = make_subplots(rows=2, cols=1, subplot_titles=('Tendencia', 'Estacionalidad'))

componentes = model.predict(fechas)

fig_comp.add_trace(
    go.Scatter(x=componentes['ds'], y=componentes['trend'], name='Tendencia'),
    row=1, col=1
)

fig_comp.add_trace(
    go.Scatter(x=componentes['ds'], y=componentes['yearly'], name='Estacionalidad'),
    row=2, col=1
)

fig_comp.update_layout(title='Componentes Prophet', height=700)
fig_comp.show()

In [ ]:
# Estadisticas descriptivas
print("ESTADISTICAS HISTORICAS")
print(f"Media: {fechas['y'].mean():.2f}")
print(f"Mediana: {fechas['y'].median():.2f}")
print(f"Desviacion estandar: {fechas['y'].std():.2f}")
print(f"Minimo: {fechas['y'].min():.2f}")
print(f"Maximo: {fechas['y'].max():.2f}")

print("\nESTADISTICAS PREDICCIONES")
print(f"Media predicha: {predicciones_futuras['yhat'].mean():.2f}")
print(f"Mediana predicha: {predicciones_futuras['yhat'].median():.2f}")
print(f"Desviacion estandar: {predicciones_futuras['yhat'].std():.2f}")
print(f"Minimo predicho: {predicciones_futuras['yhat'].min():.2f}")
print(f"Maximo predicho: {predicciones_futuras['yhat'].max():.2f}")

# Umbrales de sequia
percentil_10 = np.percentile(fechas['y'], 10)
percentil_25 = np.percentile(fechas['y'], 25)
percentil_75 = np.percentile(fechas['y'], 75)
percentil_90 = np.percentile(fechas['y'], 90)

print(f"\nUMBRALES DE SEQUIA")
print(f"Sequia severa: < {percentil_10:.2f}")
print(f"Sequia moderada: < {percentil_25:.2f}")
print(f"Situacion buena: > {percentil_75:.2f}")
print(f"Situacion excelente: > {percentil_90:.2f}")

# Analisis por años
print(f"\nANALISIS ANUAL")
años_riesgo = []
for año in range(2022, 2034):
    pred_año = predicciones_futuras[predicciones_futuras['ds'].dt.year == año]
    if len(pred_año) > 0:
        promedio = pred_año['yhat'].mean()
        if promedio < percentil_25:
            estado = "RIESGO SEQUIA"
            años_riesgo.append(año)
        elif promedio > percentil_75:
            estado = "BUENA"
        else:
            estado = "NORMAL"
        print(f"{año}: {promedio:.1f} - {estado}")

# Tendencias
ultimo_historico = fechas['y'].iloc[-1]
ultima_prediccion = predicciones_futuras['yhat'].iloc[-1]
tendencia = ((ultima_prediccion - ultimo_historico) / ultimo_historico) * 100

print(f"\nTENDENCIAS")
print(f"Ultimo valor historico: {ultimo_historico:.2f}")
print(f"Ultima prediccion: {ultima_prediccion:.2f}")
print(f"Cambio total 12 años: {tendencia:+.2f}%")
print(f"Años con riesgo sequia: {len(años_riesgo)}")
if años_riesgo:
    print(f"Años criticos: {años_riesgo}")

ESTADISTICAS HISTORICAS
Media: 661.77
Mediana: 667.41
Desviacion estandar: 131.45
Minimo: 329.24
Maximo: 907.90

ESTADISTICAS PREDICCIONES
Media predicha: 750.92
Mediana predicha: 747.67
Desviacion estandar: 71.36
Minimo predicho: 624.07
Maximo predicho: 887.14

UMBRALES DE SEQUIA
Sequia severa: < 488.48
Sequia moderada: < 573.56
Situacion buena: > 772.47
Situacion excelente: > 827.39

ANALISIS ANUAL
2022: 726.7 - NORMAL
2023: 731.9 - NORMAL
2024: 735.4 - NORMAL
2025: 742.3 - NORMAL
2026: 747.4 - NORMAL
2027: 752.6 - NORMAL
2028: 756.2 - NORMAL
2029: 763.0 - NORMAL
2030: 768.2 - NORMAL
2031: 773.3 - BUENA
2032: 776.9 - BUENA
2033: 795.7 - BUENA

TENDENCIAS
Ultimo valor historico: 802.49
Ultima prediccion: 833.86
Cambio total 12 años: +3.91%
Años con riesgo sequia: 0

In [ ]:
# Comparar solo en el período histórico
df_merge_total = pd.merge(fechas, predicciones[['ds', 'yhat']], on='ds', how='inner')

# Extraer valores reales y predichos
y_true_total = df_merge_total['y'].values
y_pred_total = df_merge_total['yhat'].values

# Calcular métricas
r2_total = r2_score(y_true_total, y_pred_total)
mae_total = mean_absolute_error(y_true_total, y_pred_total)
rmse_total = np.sqrt(mean_squared_error(y_true_total, y_pred_total))

# MAPE corregido (evitando división por cero)
non_zero_mask = y_true_total != 0
mape_total = np.mean(np.abs((y_true_total[non_zero_mask] - y_pred_total[non_zero_mask]) / y_true_total[non_zero_mask])) * 100

# Mostrar métricas del modelo total
print(f"\nMétricas del modelo Prophet TOTAL del sistema:")
print(f"R²: {r2_total:.4f}")
print(f"MAE: {mae_total:.2f}")
print(f"RMSE: {rmse_total:.2f}")
print(f"MAPE: {mape_total:.2f}%")
print(f"Accuracy aproximada: {100 - mape_total:.2f}%")

# Métricas adicionales para el modelo total
print(f"\nMétricas adicionales:")
print(f"Número de observaciones: {len(y_true_total)}")
print(f"Media de valores reales: {np.mean(y_true_total):.2f}")
print(f"Media de predicciones: {np.mean(y_pred_total):.2f}")
print(f"Diferencia de medias: {np.mean(y_pred_total) - np.mean(y_true_total):.2f}")

# Comparación con métricas individuales
if 'mape' in locals():
    print(f"\nComparación:")
    print(f"MAPE individual (promedio): {mape:.2f}%")
    print(f"MAPE total del sistema: {mape_total:.2f}%")
    print(f"Diferencia MAPE: {mape_total - mape:.2f}%")

Métricas del modelo Prophet TOTAL del sistema:
R²: 0.3400
MAE: 89.64
RMSE: 106.60
MAPE: 15.14%
Accuracy aproximada: 84.86%

Métricas adicionales:
Número de observaciones: 279
Media de valores reales: 661.77
Media de predicciones: 661.69
Diferencia de medias: -0.08

Comparación:
MAPE individual (promedio): 36.08%
MAPE total del sistema: 15.14%
Diferencia MAPE: -20.94%

In [ ]:
# PREGUNTA 1: ¿Qué embalse tiene más diferencia en su max y min de agua?

print("PREGUNTA 1: Embalse con mayor diferencia max-min")
print()
# Obtener columnas de embalses
columnas_embalses = [col for col in df_pivot.columns if col not in ['year', 'month']]

# Calcular diferencias para cada embalse
diferencias_embalses = {}

for embalse in columnas_embalses:
    datos_embalse = df_pivot[embalse].dropna()

    if len(datos_embalse) > 0:
        max_val = datos_embalse.max()
        min_val = datos_embalse.min()
        diferencia = max_val - min_val

        diferencias_embalses[embalse] = {
            'max': max_val,
            'min': min_val,
            'diferencia': diferencia,
            'registros': len(datos_embalse)
        }

# Ordenar por diferencia descendente
embalses_ordenados = sorted(diferencias_embalses.items(),
                           key=lambda x: x[1]['diferencia'],
                           reverse=True)

# Respuesta final
embalse_ganador = embalses_ordenados[0][0]
datos_ganador = embalses_ordenados[0][1]

print("RESPUESTA:")
print(f"El embalse con mayor diferencia entre máximo y mínimo es:")
print(f"'{embalse_ganador}'")
print(f"Diferencia: {datos_ganador['diferencia']:.2f} hm³")
print(f"(Máximo: {datos_ganador['max']:.2f} hm³, Mínimo: {datos_ganador['min']:.2f} hm³)")

PREGUNTA 1: Embalse con mayor diferencia max-min

RESPUESTA:
El embalse con mayor diferencia entre máximo y mínimo es:
'RioLozoya_ElAtazar'
Diferencia: 275.66 hm³
(Máximo: 423.88 hm³, Mínimo: 148.22 hm³)

In [ ]:
print("PREGUNTA 2: ¿Cuándo se produce sequía?")
print()
# Definir umbrales de sequía basados en datos históricos
datos_historicos = fechas['y']
umbral_sequia_moderada = np.percentile(datos_historicos, 25)  # Percentil 25
umbral_sequia_severa = np.percentile(datos_historicos, 10)    # Percentil 10

print(f"Umbrales definidos basados en datos históricos:")
print(f"- Sequía MODERADA: < {umbral_sequia_moderada:.2f} hm³ (percentil 25)")
print(f"- Sequía SEVERA: < {umbral_sequia_severa:.2f} hm³ (percentil 10)")
print(f"- Capacidad promedio histórica: {datos_historicos.mean():.2f} hm³")
print()

# Analizar predicciones futuras año por año
años_sequia_moderada = []
años_sequia_severa = []
meses_sequia = []

print("Análisis de predicciones año por año:")
print("-" * 40)

for año in range(2022, 2034):  # 12 años de predicción
    pred_año = predicciones_futuras[predicciones_futuras['ds'].dt.year == año]

    if len(pred_año) > 0:
        promedio_año = pred_año['yhat'].mean()
        minimo_año = pred_año['yhat'].min()

        # Clasificar el año
        if promedio_año < umbral_sequia_severa:
            estado = "SEQUÍA SEVERA"
            años_sequia_severa.append(año)
        elif promedio_año < umbral_sequia_moderada:
            estado = "SEQUÍA MODERADA"
            años_sequia_moderada.append(año)
        else:
            estado = "NORMAL"

        print(f"{año}: {promedio_año:.1f} hm³ (mín: {minimo_año:.1f}) - {estado}")

        # Detectar meses específicos con sequía
        meses_con_sequia = pred_año[pred_año['yhat'] < umbral_sequia_moderada]
        for _, mes in meses_con_sequia.iterrows():
            tipo_sequia = 'SEVERA' if mes['yhat'] < umbral_sequia_severa else 'MODERADA'
            meses_sequia.append({
                'fecha': mes['ds'],
                'valor': mes['yhat'],
                'tipo': tipo_sequia
            })

print()
print("RESPUESTA:")

# Respuesta sobre sequía
años_sequia = list(set(años_sequia_moderada + años_sequia_severa))

if len(años_sequia) > 0:
    print("SÍ se detecta riesgo de sequía en las predicciones:")
    print()

    if len(años_sequia_severa) > 0:
        print(f"SEQUÍA SEVERA detectada en: {años_sequia_severa}")
        print(f"Primer año con sequía severa: {min(años_sequia_severa)}")
        print()

    if len(años_sequia_moderada) > 0:
        años_solo_moderada = [año for año in años_sequia_moderada if año not in años_sequia_severa]
        if años_solo_moderada:
            print(f"SEQUÍA MODERADA detectada en: {años_solo_moderada}")
            print()

    print(f"Resumen temporal:")
    print(f"- Primer año con sequía: {min(años_sequia)}")
    print(f"- Total años afectados: {len(años_sequia)} de 12")
    print(f"- Porcentaje de años con sequía: {(len(años_sequia)/12)*100:.1f}%")

    if len(meses_sequia) > 0:
        primer_mes = min(meses_sequia, key=lambda x: x['fecha'])
        print(f"- Primer mes de sequía: {primer_mes['fecha'].strftime('%B %Y')}")
        print(f"  Valor: {primer_mes['valor']:.2f} hm³ ({primer_mes['tipo']})")
        print(f"- Total meses con sequía: {len(meses_sequia)}")

else:
    print("NO se detecta riesgo de sequía")
    print("Las predicciones se mantienen por encima del umbral de sequía moderada")
    print(f"Todas las predicciones anuales superan {umbral_sequia_moderada:.2f} hm³")

PREGUNTA 2: ¿Cuándo se produce sequía?

Umbrales definidos basados en datos históricos:
- Sequía MODERADA: < 573.56 hm³ (percentil 25)
- Sequía SEVERA: < 488.48 hm³ (percentil 10)
- Capacidad promedio histórica: 661.77 hm³

Análisis de predicciones año por año:
----------------------------------------
2022: 726.7 hm³ (mín: 629.5) - NORMAL
2023: 731.9 hm³ (mín: 635.0) - NORMAL
2024: 735.4 hm³ (mín: 639.4) - NORMAL
2025: 742.3 hm³ (mín: 644.8) - NORMAL
2026: 747.4 hm³ (mín: 650.3) - NORMAL
2027: 752.6 hm³ (mín: 655.8) - NORMAL
2028: 756.2 hm³ (mín: 660.1) - NORMAL
2029: 763.0 hm³ (mín: 665.5) - NORMAL
2030: 768.2 hm³ (mín: 671.0) - NORMAL
2031: 773.3 hm³ (mín: 676.5) - NORMAL
2032: 776.9 hm³ (mín: 680.8) - NORMAL
2033: 795.7 hm³ (mín: 762.4) - NORMAL

RESPUESTA:
====================
NO se detecta riesgo significativo de sequía
Las predicciones se mantienen por encima del umbral de sequía moderada
Todas las predicciones anuales superan 573.56 hm³

In [ ]:
print("PREGUNTA 3: ¿Podemos asegurar una respuesta segura?")
print()

# Análisis de calidad de datos
años_datos = df_pivot['year'].max() - df_pivot['year'].min() + 1
total_registros = len(fechas)
registros_esperados = años_datos * 12
completitud = (total_registros / registros_esperados) * 100

print("1. CALIDAD DE LOS DATOS:")
print("-" * 25)
print(f"- Período histórico: {años_datos} años ({df_pivot['year'].min()}-{df_pivot['year'].max()})")
print(f"- Registros disponibles: {total_registros}")
print(f"- Registros esperados: {registros_esperados}")
print(f"- Completitud temporal: {completitud:.1f}%")

print(f"\n2. CALIDAD DEL MODELO PROPHET:")
print("-" * 30)
print(f"- R² (coeficiente determinación): {r2_total:.3f}")
print(f"  El modelo explica {r2_total*100:.1f}% de la varianza")
print(f"- MAPE (error porcentual): {mape_total:.2f}%")
print(f"- Accuracy estimada: {100-mape_total:.2f}%")
print(f"- MAE (error absoluto medio): {mae_total:.2f} hm³")
print(f"- RMSE (error cuadrático medio): {rmse_total:.2f} hm³")

PREGUNTA 3: ¿Podemos asegurar una respuesta segura?

1. CALIDAD DE LOS DATOS:
-------------------------
- Período histórico: 24 años (1998-2021)
- Registros disponibles: 279
- Registros esperados: 288
- Completitud temporal: 96.9%

2. CALIDAD DEL MODELO PROPHET:
------------------------------
- R² (coeficiente determinación): 0.340
  El modelo explica 34.0% de la varianza
- MAPE (error porcentual): 15.14%
- Accuracy estimada: 84.86%
- MAE (error absoluto medio): 89.64 hm³
- RMSE (error cuadrático medio): 106.60 hm³

## **SARIMAX**

Predicción de 12 años por embalse, no total de agua, sino dividida en embalses.

In [ ]:
import plotly.graph_objects as go
from statsmodels.tsa.arima.model import ARIMA
import pandas as pd

resultados_arima = {}

for embalse, df in dfs_por_embalse.items():
    df_model = df.copy()

    meses_dict = {
        'enero': '01', 'febrero': '02', 'marzo': '03', 'abril': '04',
        'mayo': '05', 'junio': '06', 'julio': '07', 'agosto': '08',
        'septiembre': '09', 'octubre': '10', 'noviembre': '11', 'diciembre': '12'
    }
    df_model['month_num'] = df_model['month'].map(meses_dict).astype(str)
    df_model['ds'] = pd.to_datetime(df_model['year'].astype(str) + '-' + df_model['month_num'] + '-01')
    df_model = df_model[['ds', 'cub_hec']].set_index('ds').sort_index()

    df_model = df_model.asfreq('MS')

    # Entrenar ARIMA simple (p,d,q)
    model = ARIMA(df_model, order=(1,1,1), seasonal_order=(1,1,1,12))
    model_fit = model.fit()

    # Predicción a 12 años (144 meses)
    forecast = model_fit.get_forecast(steps=144)
    pred_ci = forecast.conf_int()

    # Fechas futuras para el forecast
    future_dates = pd.date_range(start=df_model.index[-1] + pd.DateOffset(months=1), periods=144, freq='MS')

    # Guardamos resultados
    resultados_arima[embalse] = {
        'model': model_fit,
        'historical': df_model,
        'forecast': forecast.predicted_mean,
        'conf_int': pred_ci,
        'future_dates': future_dates
    }

    fig = go.Figure()

    # Datos históricos
    fig.add_trace(go.Scatter(
        x=df_model.index, y=df_model['cub_hec'],
        mode='lines', name='Histórico'
    ))

    # Predicción
    fig.add_trace(go.Scatter(
        x=future_dates, y=forecast.predicted_mean,
        mode='lines', name='Predicción ARIMA'
    ))

    # Intervalo de confianza
    fig.add_trace(go.Scatter(
        x=list(future_dates) + list(future_dates[::-1]),
        y=list(pred_ci.iloc[:,0]) + list(pred_ci.iloc[:,1][::-1]),
        fill='toself',
        fillcolor='rgba(0,100,80,0.2)',
        line=dict(color='rgba(255,255,255,0)'),
        hoverinfo="skip",
        showlegend=True,
        name='Intervalo confianza'
    ))

    fig.update_layout(
        title=f"Predicción SARIMA para {embalse}",
        xaxis_title='Fecha',
        yaxis_title='Hectómetros cúbicos',
        template='plotly_white',
        height=500
    )

    fig.show()

/usr/local/lib/python3.11/dist-packages/statsmodels/tsa/statespace/sarimax.py:966: UserWarning:

Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.

/usr/local/lib/python3.11/dist-packages/statsmodels/tsa/statespace/sarimax.py:978: UserWarning:

Non-invertible starting MA parameters found. Using zeros as starting parameters.

Estadisticas para la predicción individual de embalses:

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

y_true_total = []
y_pred_total = []

for embalse, resultados in resultados_arima.items():
    df_hist = resultados['historical']  # Serie histórica con índice datetime
    pred = resultados['model'].predict(start=df_hist.index[0], end=df_hist.index[-1])

    # Guardamos reales y predichos para el histórico
    y_true_total.extend(df_hist['cub_hec'].values)
    y_pred_total.extend(pred.values)

# Convertimos a numpy arrays para métricas
y_true_total = np.array(y_true_total)
y_pred_total = np.array(y_pred_total)

# Calculamos métricas
r2_total = r2_score(y_true_total, y_pred_total)
mae_total = mean_absolute_error(y_true_total, y_pred_total)
rmse_total = np.sqrt(mean_squared_error(y_true_total, y_pred_total))

# Para MAPE evitamos división por cero
non_zero_idx = y_true_total != 0
mape_total = np.mean(np.abs((y_true_total[non_zero_idx] - y_pred_total[non_zero_idx]) / y_true_total[non_zero_idx])) * 100

accuracy = 100 - mape_total

print(f"R² total global SARIMA: {r2_total:.4f}")
print(f"MAE total SARIMA: {mae_total:.4f}")
print(f"RMSE total SARIMA: {rmse_total:.4f}")
print(f"MAPE total SARIMA: {mape_total:.4f}%")
print(f"Accuracy aproximada SARIMA: {accuracy:.2f}%")

R² total global SARIMA: 0.9882
MAE total SARIMA: 3.2753
RMSE total SARIMA: 8.9012
MAPE total SARIMA: 13.6755%
Accuracy aproximada SARIMA: 86.32%

Ahora si, predicción total de los embalses:

In [ ]:
meses_dict = {
    'enero': '01', 'febrero': '02', 'marzo': '03', 'abril': '04',
    'mayo': '05', 'junio': '06', 'julio': '07', 'agosto': '08',
    'septiembre': '09', 'octubre': '10', 'noviembre': '11', 'diciembre': '12'
}

# Crear serie temporal total desde df_pivot
df_total_sarimax = df_pivot.copy()
df_total_sarimax['month_num'] = df_total_sarimax['month'].map(meses_dict).astype(str)
df_total_sarimax['ds'] = pd.to_datetime(df_total_sarimax['year'].astype(str) + '-' +
                                       df_total_sarimax['month_num'] + '-01')

# Sumar todos los embalses para obtener capacidad total
columnas_embalses = [col for col in df_total_sarimax.columns if col not in ['year', 'month', 'month_num', 'ds']]
df_total_sarimax['total_sistema'] = df_total_sarimax[columnas_embalses].sum(axis=1, skipna=True)

# Preparar para SARIMAX
df_model_total = df_total_sarimax[['ds', 'total_sistema']].set_index('ds').sort_index()
df_model_total = df_model_total.asfreq('MS')  # Frecuencia mensual

# Entrenar modelo SARIMAX para el sistema total
model_total_sarimax = ARIMA(df_model_total, order=(1,1,1), seasonal_order=(1,1,1,12))
model_fit_total = model_total_sarimax.fit()


# Predicción a 12 años (144 meses)
forecast_total = model_fit_total.get_forecast(steps=144)
pred_ci_total = forecast_total.conf_int()

# Fechas futuras para el forecast
future_dates_total = pd.date_range(
    start=df_model_total.index[-1] + pd.DateOffset(months=1),
    periods=144,
    freq='MS'
)

# Guardar resultados del modelo total
resultados_sarimax_total = {
    'model': model_fit_total,
    'historical': df_model_total,
    'forecast': forecast_total.predicted_mean,
    'conf_int': pred_ci_total,
    'future_dates': future_dates_total
}

# Mostrar algunas predicciones clave
print(f"\nPredicciones clave:")
ultimo_historico = df_model_total['total_sistema'].iloc[-1]
primera_prediccion = forecast_total.predicted_mean.iloc[0]
ultima_prediccion = forecast_total.predicted_mean.iloc[-1]

print(f"- Último valor histórico: {ultimo_historico:.2f} hm³")
print(f"- Primera predicción: {primera_prediccion:.2f} hm³")
print(f"- Última predicción (2033): {ultima_prediccion:.2f} hm³")
print(f"- Cambio total: {((ultima_prediccion - ultimo_historico) / ultimo_historico) * 100:+.2f}%")
print()

fig = go.Figure()

# Datos históricos
fig.add_trace(go.Scatter(
    x=df_model_total.index,
    y=df_model_total['total_sistema'],
    mode='lines',
    name='Histórico',
    line=dict(color='blue', width=2)
))

# Predicción
fig.add_trace(go.Scatter(
    x=future_dates_total,
    y=forecast_total.predicted_mean,
    mode='lines',
    name='Predicción SARIMAX',
    line=dict(color='red', width=2, dash='dash')
))

# Intervalo de confianza
fig.add_trace(go.Scatter(
    x=list(future_dates_total) + list(future_dates_total[::-1]),
    y=list(pred_ci_total.iloc[:,0]) + list(pred_ci_total.iloc[:,1][::-1]),
    fill='toself',
    fillcolor='rgba(255,0,0,0.2)',
    line=dict(color='rgba(255,255,255,0)'),
    hoverinfo="skip",
    showlegend=True,
    name='Intervalo confianza'
))

fig.update_layout(
    title="Predicción SARIMAX - Total Embalses",
    xaxis_title='Fecha',
    yaxis_title='Capacidad Total (hm³)',
    template='plotly_white',
    height=600
)

fig.show()

Predicciones clave:
- Último valor histórico: 802.49 hm³
- Primera predicción: 825.15 hm³
- Última predicción (2033): 729.45 hm³
- Cambio total: -9.10%

Comparación del modelo SARIMAX y Prophet:

In [ ]:
predicciones_historicas = model_fit_total.fittedvalues

# Los datos históricos
datos_reales = df_model_total['total_sistema']

mask_validos = ~(predicciones_historicas.isna() | datos_reales.isna())
y_true_sarimax = datos_reales[mask_validos].values
y_pred_sarimax = predicciones_historicas[mask_validos].values

print(f"Datos para evaluación:")
print(f"- Observaciones válidas: {len(y_true_sarimax)}")
print(f"- Período evaluado: {datos_reales[mask_validos].index.min().strftime('%Y-%m')} a {datos_reales[mask_validos].index.max().strftime('%Y-%m')}")

# Calcular métricas
r2_sarimax = r2_score(y_true_sarimax, y_pred_sarimax)
mae_sarimax = mean_absolute_error(y_true_sarimax, y_pred_sarimax)
rmse_sarimax = np.sqrt(mean_squared_error(y_true_sarimax, y_pred_sarimax))

# MAPE corregido
non_zero_mask = y_true_sarimax != 0
mape_sarimax = np.mean(np.abs((y_true_sarimax[non_zero_mask] - y_pred_sarimax[non_zero_mask]) / y_true_sarimax[non_zero_mask])) * 100

# Mostrar métricas del modelo SARIMAX
print(f"\nMétricas del modelo SARIMAX TOTAL del sistema:")
print(f"R²: {r2_sarimax:.4f}")
print(f"MAE: {mae_sarimax:.2f}")
print(f"RMSE: {rmse_sarimax:.2f}")
print(f"MAPE: {mape_sarimax:.2f}%")
print(f"Accuracy aproximada: {100 - mape_sarimax:.2f}%")

# Comparación con Prophet
if 'mape_total' in locals():
    print(f"\nComparación Prophet vs SARIMAX:")
    print(f"MAPE Prophet: {mape_total:.2f}%")
    print(f"MAPE SARIMAX: {mape_sarimax:.2f}%")
    print(f"Diferencia MAPE: {mape_sarimax - mape_total:.2f}%")

    if 'r2_total' in locals():
        print(f"R² Prophet: {r2_total:.4f}")
        print(f"R² SARIMAX: {r2_sarimax:.4f}")
        print(f"Diferencia R²: {r2_sarimax - r2_total:.4f}")

    # Comparativa
    if mape_sarimax < mape_total:
        print(f"SARIMAX tiene menor error (mejor)")
    elif mape_sarimax > mape_total:
        print(f"Prophet tiene menor error (mejor)")
    else:
        print(f"Ambos modelos tienen error similar")

Datos para evaluación:
- Observaciones válidas: 279
- Período evaluado: 1998-01 a 2021-03

Métricas del modelo SARIMAX TOTAL del sistema:
R²: 0.7600
MAE: 28.40
RMSE: 64.28
MAPE: 4.34%
Accuracy aproximada: 95.66%

Comparación Prophet vs SARIMAX:
MAPE Prophet: 13.68%
MAPE SARIMAX: 4.34%
Diferencia MAPE: -9.33%
R² Prophet: 0.9882
R² SARIMAX: 0.7600
Diferencia R²: -0.2282
SARIMAX tiene menor error (mejor)



---

## **LSTM**

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import Input
import numpy as np
import pandas as pd
import random
import plotly.graph_objects as go
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

print("LSTM TOTAL")
print()

# Fijar seeds para reproducibilidad
tf.random.set_seed(42)
np.random.seed(42)
random.seed(42)

# Funciones auxiliares (iguales a tu código)
def create_dataset(features, targets, window_size=24):
    X, y = [], []
    for i in range(len(targets) - window_size):
        X.append(features[i:i+window_size])
        y.append(targets[i+window_size])
    return np.array(X), np.array(y)

def predict_model(model, X):
    return model(X, training=False)

# Preparar datos totales del sistema
meses_dict = {
    'enero': 1, 'febrero': 2, 'marzo': 3, 'abril': 4,
    'mayo': 5, 'junio': 6, 'julio': 7, 'agosto': 8,
    'septiembre': 9, 'octubre': 10, 'noviembre': 11, 'diciembre': 12
}

# Crear dataset total desde df_pivot
df_lstm_total = df_pivot.copy()
df_lstm_total['month_num'] = df_lstm_total['month'].map(meses_dict).astype(int)
df_lstm_total['ds'] = pd.to_datetime(df_lstm_total['year'].astype(str) + '-' +
                                    df_lstm_total['month_num'].astype(str) + '-01')

# Sumar todos los embalses
columnas_embalses = [col for col in df_lstm_total.columns if col not in ['year', 'month', 'month_num', 'ds']]
df_lstm_total['total_sistema'] = df_lstm_total[columnas_embalses].sum(axis=1, skipna=True)

# Preparar para LSTM
df_lstm_total = df_lstm_total[['ds', 'total_sistema', 'month_num']].set_index('ds').sort_index()


# Features cíclicas de mes
df_lstm_total['month_sin'] = np.sin(2 * np.pi * df_lstm_total['month_num'] / 12)
df_lstm_total['month_cos'] = np.cos(2 * np.pi * df_lstm_total['month_num'] / 12)

# Escalado del target
scaler_total = MinMaxScaler()
df_lstm_total['total_scaled'] = scaler_total.fit_transform(df_lstm_total[['total_sistema']])

# Crear lag features
for lag in range(1, 4):
    df_lstm_total[f'lag_{lag}'] = df_lstm_total['total_scaled'].shift(lag)

# Eliminar NaN
df_lstm_total = df_lstm_total.dropna()

# Escalar features
scaler_feats_total = MinMaxScaler()
df_lstm_total[['month_sin', 'month_cos', 'lag_1', 'lag_2', 'lag_3']] = scaler_feats_total.fit_transform(
    df_lstm_total[['month_sin', 'month_cos', 'lag_1', 'lag_2', 'lag_3']])

print(f"Features preparadas: {len(df_lstm_total)} registros válidos")

# Preparar matrices
features_total = df_lstm_total[['total_scaled', 'month_sin', 'month_cos', 'lag_1', 'lag_2', 'lag_3']].values
targets_total = df_lstm_total['total_scaled'].values

# Configuración de ventana
window_size = 24

# Crear datasets
X_total, y_total = create_dataset(features_total, targets_total, window_size)

# División train/val/test 70/15/15
train_end = int(len(X_total) * 0.7)
val_end = int(len(X_total) * 0.85)

X_train_total = X_total[:train_end]
y_train_total = y_total[:train_end]
X_val_total = X_total[train_end:val_end]
y_val_total = y_total[train_end:val_end]
X_test_total = X_total[val_end:]
y_test_total = y_total[val_end:]

print()
print(f"División de datos:")
print(f"- Entrenamiento: {len(X_train_total)} muestras")
print(f"- Validación: {len(X_val_total)} muestras")
print(f"- Test: {len(X_test_total)} muestras")

# Modelo Bidirectional LSTM

model_total = Sequential([
    Input(shape=(window_size, features_total.shape[1])),
    Bidirectional(LSTM(64, return_sequences=True)),
    Dropout(0.3),
    Bidirectional(LSTM(32)),
    Dropout(0.3),
    Dense(1)
])

model_total.compile(optimizer='adam', loss='mse')

early_stop = EarlyStopping(monitor='val_loss', patience=25, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, verbose=1)


# Entrenar modelo
history = model_total.fit(
    X_train_total, y_train_total,
    epochs=150,
    batch_size=16,
    validation_data=(X_val_total, y_val_total),
    callbacks=[early_stop, reduce_lr],
    verbose=0
)

y_pred_scaled_total = predict_model(model_total, X_test_total).numpy()
y_pred_total_final = scaler_total.inverse_transform(y_pred_scaled_total)
y_test_orig_total = scaler_total.inverse_transform(y_test_total.reshape(-1, 1))

# Fechas para test
test_dates_total = df_lstm_total.index[window_size + val_end: window_size + val_end + len(y_test_total)]

# Métricas
r2_lstm_total = r2_score(y_test_orig_total, y_pred_total_final)
mae_lstm_total = mean_absolute_error(y_test_orig_total, y_pred_total_final)
rmse_lstm_total = np.sqrt(mean_squared_error(y_test_orig_total, y_pred_total_final))
mape_lstm_total = np.mean(np.abs((y_test_orig_total - y_pred_total_final) / y_test_orig_total)) * 100
accuracy_lstm_total = 100 - mape_lstm_total

print(f"Métricas del modelo LSTM TOTAL:")
print(f"R²: {r2_lstm_total:.4f}")
print(f"MAE: {mae_lstm_total:.2f}")
print(f"RMSE: {rmse_lstm_total:.2f}")
print(f"MAPE: {mape_lstm_total:.2f}%")
print(f"Accuracy: {accuracy_lstm_total:.2f}%")

# Comparación con otros modelos
if 'mape_total' in locals() and 'mape_sarimax' in locals():
    print(f"\nComparación de modelos:")
    print(f"Prophet MAPE: {mape_total:.2f}%")
    print(f"SARIMAX MAPE: {mape_sarimax:.2f}%")
    print(f"LSTM MAPE: {mape_lstm_total:.2f}%")

    mejor_modelo = min([
        ('Prophet', mape_total),
        ('SARIMAX', mape_sarimax),
        ('LSTM', mape_lstm_total)
    ], key=lambda x: x[1])

    print(f"Mejor modelo: {mejor_modelo[0]} (MAPE: {mejor_modelo[1]:.2f}%)")

# Guardar resultados
resultados_lstm_total = {
    'model': model_total,
    'scaler': scaler_total,
    'scaler_feats': scaler_feats_total,
    'X_test': X_test_total,
    'y_test': y_test_total,
    'y_pred': y_pred_total_final,
    'y_test_orig': y_test_orig_total,
    'test_dates': test_dates_total,
    'r2': r2_lstm_total,
    'mae': mae_lstm_total,
    'rmse': rmse_lstm_total,
    'mape': mape_lstm_total,
    'accuracy': accuracy_lstm_total,
    'df_lstm': df_lstm_total,
    'history': history
}

print()
fig = go.Figure()

# Datos reales
fig.add_trace(go.Scatter(
    x=test_dates_total,
    y=y_test_orig_total.flatten(),
    mode='lines+markers',
    name='Real',
    line=dict(color='blue', width=2)
))

# Predicción LSTM
fig.add_trace(go.Scatter(
    x=test_dates_total,
    y=y_pred_total_final.flatten(),
    mode='lines+markers',
    name='Predicción LSTM',
    line=dict(color='red', width=2, dash='dash')
))

fig.update_layout(
    title=f"LSTM Total del Sistema - Predicción vs Real<br>R²={r2_lstm_total:.4f} - Accuracy={accuracy_lstm_total:.2f}%",
    xaxis_title='Fecha',
    yaxis_title='Capacidad Total (hm³)',
    template='plotly_white',
    height=600
)

fig.show()

LSTM TOTAL

Features preparadas: 276 registros válidos

División de datos:
- Entrenamiento: 176 muestras
- Validación: 38 muestras
- Test: 38 muestras

Epoch 45: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 68: ReduceLROnPlateau reducing learning rate to 0.0002500000118743628.

Epoch 85: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.

Epoch 95: ReduceLROnPlateau reducing learning rate to 6.25000029685907e-05.
Métricas del modelo LSTM TOTAL:
R²: 0.6992
MAE: 43.11
RMSE: 55.68
MAPE: 6.22%
Accuracy: 93.78%

Comparación de modelos:
Prophet MAPE: 13.68%
SARIMAX MAPE: 4.34%
LSTM MAPE: 6.22%
Mejor modelo: SARIMAX (MAPE: 4.34%)

## **Predicción 12 Años**

In [ ]:
n_meses = 144
window_size = 24

# Obtener datos del modelo entrenado
model = resultados_lstm_total['model']
scaler = resultados_lstm_total['scaler']
scaler_feats = resultados_lstm_total['scaler_feats']
df_lstm = resultados_lstm_total['df_lstm']
X_test = resultados_lstm_total['X_test']
test_dates = resultados_lstm_total['test_dates']

# Última fecha de los datos
last_date = test_dates[-1]

# Inicializar predicción
future_preds_scaled = []
current_window = X_test[-1].copy()
current_date = last_date

# Bucle de predicción iterativa
for i in range(n_meses):
    # Predecir siguiente mes
    pred_scaled = model.predict(current_window[np.newaxis, :, :], verbose=0)[0, 0]
    future_preds_scaled.append(pred_scaled)

    current_date += pd.DateOffset(months=1)
    next_month_num = current_date.month

    next_month_sin = np.sin(2 * np.pi * next_month_num / 12)
    next_month_cos = np.cos(2 * np.pi * next_month_num / 12)

    # Preparar lags actualizados
    lag_1 = pred_scaled
    lag_2 = current_window[-1, 0]
    lag_3 = current_window[-2, 0]

    # Crear DataFrame para escalar features
    feats_df = pd.DataFrame([[next_month_sin, next_month_cos, lag_1, lag_2, lag_3]],
                            columns=['month_sin', 'month_cos', 'lag_1', 'lag_2', 'lag_3'])

    # Escalar features
    feats_scaled = scaler_feats.transform(feats_df)[0]

    # Crear nueva fila para la ventana
    new_row = np.array([pred_scaled] + list(feats_scaled))

    # Actualizar ventana deslizante
    current_window = np.vstack([current_window[1:], new_row])

# Desescalar predicciones
future_preds = scaler.inverse_transform(np.array(future_preds_scaled).reshape(-1, 1)).flatten()

# Crear fechas futuras
future_dates = pd.date_range(
    start=last_date + pd.DateOffset(months=1),
    periods=n_meses,
    freq='MS'
)

try:
    historico_start = future_dates[0] - pd.DateOffset(years=5)
    historico = df_lstm.loc[df_lstm.index >= historico_start].copy()
    if len(historico) > 0:
        historico['total_original'] = scaler.inverse_transform(historico[['total_scaled']])
    else:
        historico = df_lstm.tail(60).copy()
        historico['total_original'] = scaler.inverse_transform(historico[['total_scaled']])
except:
    historico = df_lstm.tail(60).copy()
    historico['total_original'] = scaler.inverse_transform(historico[['total_scaled']])

fig = go.Figure()

# Datos históricos (últimos 5 años)
fig.add_trace(go.Scatter(
    x=historico.index,
    y=historico['total_original'].values,
    mode='lines+markers',
    name='Histórico (5 años)',
    line=dict(color='blue', width=2),
    marker=dict(size=4)
))

# Predicciones futuras
fig.add_trace(go.Scatter(
    x=future_dates,
    y=future_preds,
    mode='lines+markers',
    name='Predicción 12 años',
    line=dict(color='red', width=3, dash='dash'),
    marker=dict(size=4)
))


fig.add_annotation(
    x=last_date,
    y=historico['total_original'].iloc[-1] if len(historico) > 0 else future_preds[0],
    text="Inicio<br>Predicción",
    showarrow=True,
    arrowhead=2,
    arrowcolor="gray",
    bgcolor="white",
    bordercolor="gray"
)

fig.update_layout(
    title=f"Predicción LSTM: Sistema Total de Embalses - 12 años<br>"
          f"Desde {future_dates[0].strftime('%B %Y')} hasta {future_dates[-1].strftime('%B %Y')}",
    xaxis_title="Fecha",
    yaxis_title="Capacidad Total (hm³)",
    template="plotly_white",
    height=600,
    hovermode='x unified'
)

# Mostrar gráfico
fig.show()

prediccion_12_años = {
    'fechas': future_dates,
    'predicciones': future_preds,
    'predicciones_escaladas': future_preds_scaled,
    'modelo': model,
    'scaler': scaler,
    'historico': historico,
    'metricas_modelo': {
        'r2': resultados_lstm_total['r2'],
        'mape': resultados_lstm_total['mape'],
        'accuracy': resultados_lstm_total['accuracy']
    }
}



---

\